--# Copyright IBM Corp. All Rights Reserved.
--# SPDX-License-Identifier: Apache-2.0

/*
 * Convert a string from latin-1 codepage to UTF-8
 */

/*
 * Replaces the 96 Latin-1 code-points with Unicode UTF-8 Code points
 * 
 * I.e. Performs a codepage conversion from Latin-1 to UTF-8
 * 
 */
CREATE OR REPLACE FUNCTION DB_LATIN1_TO_UTF8(I VARCHAR(32672 OCTETS))
    NO EXTERNAL ACTION
    DETERMINISTIC
RETURNS VARCHAR(32672 OCTETS)
RETURN (
REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
 I
,x'C3',x'C383')
,x'C2',x'C382') 
,x'A2',x'C2A2')
,x'E2',x'C3A2')
,x'A6',x'C2A6')
,x'C0',x'C380'),x'C1',x'C381')                              ,x'C4',x'C384'),x'C5',x'C385'),x'C6',x'C386'),x'C7',x'C387'),x'C8',x'C388'),x'C9',x'C389'),x'CA',x'C38A'),x'CB',x'C38B'),x'CC',x'C38C'),x'CD',x'C38D'),x'CE',x'C38E'),x'CF',x'C38F')
,x'D0',x'C390'),x'D1',x'C391'),x'D2',x'C392'),x'D3',x'C393'),x'D4',x'C394'),x'D5',x'C395'),x'D6',x'C396'),x'D7',x'C397'),x'D8',x'C398'),x'D9',x'C399'),x'DA',x'C39A'),x'DB',x'C39B'),x'DC',x'C39C'),x'DD',x'C39D'),x'DE',x'C39E'),x'DF',x'C39F')
               ,x'A1',x'C2A1')               ,x'A3',x'C2A3'),x'A4',x'C2A4'),x'A5',x'C2A5')               ,x'A7',x'C2A7'),x'A8',x'C2A8'),x'A9',x'C2A9'),x'AA',x'C2AA'),x'AB',x'C2AB'),x'AC',x'C2AC'),x'AD',x'C2AD'),x'AE',x'C2AE'),x'AF',x'C2AF')
,x'B0',x'C2B0'),x'B1',x'C2B1'),x'B2',x'C2B2'),x'B3',x'C2B3'),x'B4',x'C2B4'),x'B5',x'C2B5'),x'B6',x'C2B6'),x'B7',x'C2B7'),x'B8',x'C2B8'),x'B9',x'C2B9'),x'BA',x'C2BA'),x'BB',x'C2BB'),x'BC',x'C2BC'),x'BD',x'C2BD'),x'BE',x'C2BE'),x'BF',x'C2BF')
,x'E0',x'C3A0'),x'E1',x'C3A1')               ,x'E3',x'C3A3'),x'E4',x'C3A4'),x'E5',x'C3A5'),x'E6',x'C3A6'),x'E7',x'C3A7'),x'E8',x'C3A8'),x'E9',x'C3A9'),x'EA',x'C3AA'),x'EB',x'C3AB'),x'EC',x'C3AC'),x'ED',x'C3AD'),x'EE',x'C3AE'),x'EF',x'C3AF')
,x'F0',x'C3B0'),x'F1',x'C3B1'),x'F2',x'C3B2'),x'F3',x'C3B3'),x'F4',x'C3B4'),x'F5',x'C3B5'),x'F6',x'C3B6'),x'F7',x'C3B7'),x'F8',x'C3B8'),x'F9',x'C3B9'),x'FA',x'C3BA'),x'FB',x'C3BB'),x'FC',x'C3BC'),x'FD',x'C3BD'),x'FE',x'C3BE'),x'FF',x'C3BF')
)
