--# Copyright IBM Corp. All Rights Reserved.
--# SPDX-License-Identifier: Apache-2.0

/*
 * Returns the SQL error message for the passed SQLCODE. Returns NULL is the SQLCODE is invalid
 */

CREATE OR REPLACE FUNCTION DB_SQLERRM
(
    MSGID VARCHAR(9)
,   TOKENS VARCHAR(70)
,   TOKEN_DELIMITER VARCHAR(1)
,   LOCALE VARCHAR(33)
,   SHORTMSG INTEGER
) 
RETURNS VARCHAR(32672 OCTETS)
    CONTAINS SQL --ALLOW PARALLEL
    NO EXTERNAL ACTION
    DETERMINISTIC
BEGIN 
    DECLARE R VARCHAR(32672 OCTETS);
  DECLARE EXIT HANDLER FOR SQLEXCEPTION RETURN NULL;
  
  SET R = SYSPROC.SQLERRM ( MSGID, TOKENS, TOKEN_DELIMITER, LOCALE, SHORTMSG);
  
  RETURN R;
END
