--# Copyright IBM Corp. All Rights Reserved.
--# SPDX-License-Identifier: Apache-2.0

/*
 * CASTs the input to a BIGINT but returns NULL if the value can't be CAST successfully
 */

CREATE OR REPLACE FUNCTION DB_TO_BIGINT(i VARCHAR(64)) RETURNS BIGINT
    CONTAINS SQL ALLOW PARALLEL
    NO EXTERNAL ACTION
    DETERMINISTIC
BEGIN 
  DECLARE NOT_VALID CONDITION FOR SQLSTATE '22018';
  DECLARE EXIT HANDLER FOR NOT_VALID RETURN NULL;
  --
  RETURN CAST(i AS BIGINT);
END