#!/bin/sh
#
if [ $# != 2 ] || [ \( $1 != "-a" \) -a \( $1 != "-d" \) ]
then
   echo ""
   echo "Usage: $0 OPTION DAS_USER_HOME_DIR"
   echo ""
   echo "Options:"
   echo "  -a  Add SELinux file contexts in the given DAS user home directory"
   echo "  -d  Delete SELinux file contexts from the given DAS user home directory"
   echo ""
   echo "Examples:"
   echo "  $0 -a /home/dasusr1"
   echo "  $0 -d /home/dasusr1"
   echo ""
   exit
fi

if [ ! -d $2 ]
then
  echo "Directory $2 does not exist"
  exit
fi

semanage fcontext $1 --ftype "" --seuser user_u -t db2_file_t "$2/das(/.*)?"
semanage fcontext $1 --ftype -- --seuser user_u -t db2_exec_t "$2/das/adm/.*"
semanage fcontext $1 --ftype -- --seuser user_u -t db2_shell_script_t "$2/das/dasprofile"
semanage fcontext $1 --ftype -- --seuser user_u -t db2_shell_script_t "$2/das/userprofile"

restorecon -R $2
