--********************************************************************/
--                                                                   */
--          IBM InfoSphere Replication Server                        */
--      Version 10.2.1 for Linux, UNIX AND Windows                       */
--                                                                   */
--     Sample Q Replication migration script for UNIX AND Windows    */
--     Licensed Materials - Property of IBM                          */
--                                                                   */
--     (C) Copyright IBM Corp. 1993, 2015. All Rights Reserved       */
--                                                                   */
--     US Government Users Restricted Rights - Use, duplication      */
--     or disclosure restricted by GSA ADP Schedule Contract         */
--     with IBM Corp.                                                */
--                                                                   */
--********************************************************************/
-- Script to migrate Oracle Q Apply control tables from V10 
-- or V105FP[1-6] to V10.5 FP7 or higher
--
-- Prior to running this script, customize it to your existing 
-- Q Apply server environment:
-- (1) Locate and change all occurrences of the string !APPSCHEMA! 
--     to the name of the Q Capture schema applicable to your
--     environment
-- (2) The MCG tables need to be created only when the user ASN exists 
--     and the user migrating to 1021 has sufficient privileges to create
--     IBMQREP_MCGSYNC, IBMQREP_MCGPARMS tables in ASN schema. 
--     Uncomment the DDL for creating MCG tables including
--     IBMQREP_MCGMON which gets
--     created in !APPSCHEMA!

UPDATE !APPSCHEMA!.IBMQREP_APPLYPARMS SET ARCH_LEVEL = '1021';
UPDATE !APPSCHEMA!.IBMQREP_APPLYPARMS SET MULTI_ROW_INSERT = 'N';
ALTER TABLE !APPSCHEMA!.IBMQREP_APPLYPARMS ADD USE_APPLYCMD_TABLE CHAR(1) DEFAULT 'N' NOT NULL;
ALTER TABLE !APPSCHEMA!.IBMQREP_APPLYPARMS ADD APPLYCMD_INTERVAL NUMBER(10) DEFAULT 3000 NOT NULL;

ALTER TABLE !APPSCHEMA!.IBMQREP_RECVQUEUES ADD MCGNAME VARCHAR2(64) DEFAULT NULL;

ALTER TABLE !APPSCHEMA!.IBMQREP_RECVQUEUES ADD AGENT_STMT_CACHE_SZ NUMBER(10) DEFAULT 100 NOT NULL;

ALTER TABLE !APPSCHEMA!.IBMQREP_RECVQUEUES ADD MRI_MEMORY_LIMIT NUMBER(10) DEFAULT 1024 NOT NULL;

ALTER TABLE !APPSCHEMA!.IBMQREP_RECVQUEUES ADD BIDIAPPLY_SCHEMA VARCHAR2(128) DEFAULT NULL;


ALTER TABLE !APPSCHEMA!.IBMQREP_APPLYMON  ADD TRANS_READ NUMBER(10) ;
ALTER TABLE !APPSCHEMA!.IBMQREP_APPLYMON  ADD  DEPENDENCY_DELAY NUMBER(10);
ALTER TABLE !APPSCHEMA!.IBMQREP_APPLYMON  ADD  MCGSYNC_DELAY NUMBER(10);
ALTER TABLE !APPSCHEMA!.IBMQREP_APPLYMON  ADD  WORKQ_WAIT_TIME NUMBER(10);
ALTER TABLE !APPSCHEMA!.IBMQREP_APPLYMON  ADD  RETRY_TIME NUMBER(10);
ALTER TABLE !APPSCHEMA!.IBMQREP_APPLYMON  ADD  DBMS_TIME NUMBER(10);
ALTER TABLE !APPSCHEMA!.IBMQREP_APPLYMON  ADD  STMTS_PREPARED NUMBER(10);
ALTER TABLE !APPSCHEMA!.IBMQREP_APPLYMON  ADD NUM_MRI_STMTS_EXECUTED NUMBER(10);
ALTER TABLE !APPSCHEMA!.IBMQREP_APPLYMON  ADD ROWS_PROCESSED_MRI NUMBER(10);
ALTER TABLE !APPSCHEMA!.IBMQREP_APPLYMON  ADD CURRENT_MEMORY_STMT_CACHE NUMBER(10);
ALTER TABLE !APPSCHEMA!.IBMQREP_APPLYMON ADD UNAVAIL_RES_RETRIES NUMBER(10) DEFAULT 0 NOT NULL;


ALTER TABLE !APPSCHEMA!.IBMQREP_TARGETS ADD REPL_DROP_COL CHAR(1) DEFAULT 'Y';
ALTER TABLE !APPSCHEMA!.IBMQREP_TARGETS ADD REPL_RENAME_COL CHAR(1) DEFAULT 'Y';
ALTER TABLE !APPSCHEMA!.IBMQREP_TARGETS ADD REPL_ALTER_COL CHAR(1) DEFAULT 'Y';
ALTER TABLE !APPSCHEMA!.IBMQREP_TARGETS ADD SRC_LOCATION_ALIAS VARCHAR2(16) DEFAULT NULL;



CREATE TABLE !APPSCHEMA!.IBMQREP_APPEVTDEFS
(
 EVENTNAME VARCHAR2(64) NOT NULL ,
 QMAPNAME VARCHAR2(64) NOT NULL ,
 WORKLOADNAME VARCHAR2(64) NOT NULL ,
 TYPE VARCHAR2(26) NOT NULL ,
 EIF CHARACTER(1) DEFAULT 'N' NOT NULL ,
 CONSOLE CHARACTER(1) DEFAULT 'N' NOT NULL ,
 "TABLE" CHARACTER(1) DEFAULT 'N' NOT NULL ,
 MAX NUMBER(10),
 RESET NUMBER(10),
 EIF_WORKLOADTYPE VARCHAR2(18),
 PRIMARY KEY(QMAPNAME, TYPE, WORKLOADNAME)
);


CREATE TABLE !APPSCHEMA!.IBMQREP_APPEVENTS
(
 EVENTTIME TIMESTAMP NOT NULL ,
 WORKLOADNAME VARCHAR2(64) NOT NULL ,
 QMAPNAME VARCHAR2(64) NOT NULL ,
 TYPE VARCHAR2(33) NOT NULL ,
 THRESHOLD NUMBER(10),
 VALUE NUMBER(10),
 SYSPLEX CHARACTER(8),
 SYSTEM CHARACTER(8),
 JOBNAME CHARACTER(8),
 OLDEST_TRANS TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL 
);


CREATE INDEX !APPSCHEMA!.IX1APPEVENT ON !APPSCHEMA!.IBMQREP_APPEVENTS
(
 EVENTTIME DESC
);


CREATE TABLE !APPSCHEMA!.IBMQREP_APPLYCMD
(
 CMD_ID NUMBER(19) NOT NULL ,
 CMD_INPUT_TIME TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL ,
 CMD_ORIGINATOR VARCHAR2(128) DEFAULT USER NOT NULL ,
 CMD_TEXT VARCHAR2(1024) NOT NULL ,
 CMD_STATE CHARACTER(1) DEFAULT 'P' NOT NULL ,
 CMD_RESULT_MSG VARCHAR2(1024) DEFAULT NULL,
 CMD_STATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL ,
 CMD_RESULT_RC NUMBER(10) DEFAULT NULL
);

CREATE INDEX !APPSCHEMA!.IX1APPLYCMD ON !APPSCHEMA!.IBMQREP_APPLYCMD
(
 CMD_ID
);

CREATE SEQUENCE !APPSCHEMA!.APPLYCMD_SEQ START WITH 1 INCREMENT BY 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER !APPSCHEMA!.APPLYCMD_BEFORE_INSERT
BEFORE INSERT
   ON !APPSCHEMA!.IBMQREP_APPLYCMD
   FOR EACH ROW
   
DECLARE
   v_seq number(19);
   
BEGIN

  --Generate the CMD_ID value from APPLYCMD_SEQ
   SELECT !APPSCHEMA!.APPLYCMD_SEQ.NEXTVAL INTO v_seq
   FROM dual;
   
      
     --Update the sequence value before INSERT
   :new.CMD_ID := v_seq;
   
END;
/
CREATE TABLE !APPSCHEMA!.IBMQREP_APPLYCMDOUT
(
 CMD_ID NUMBER(19) NOT NULL ,
 CMD_SEQUENCE NUMBER(5) NOT NULL ,
 CMD_OUTPUT VARCHAR2(4000) NOT NULL 
);


CREATE INDEX !APPSCHEMA!.IX1APPLYCMDOUT ON !APPSCHEMA!.IBMQREP_APPLYCMDOUT
(
 CMD_ID,
 CMD_SEQUENCE
);

-- Do not the change the ASN schema name for the following two tables 
-- IBMQREP_MCGSYNC and IBMQREP_MCGPARMS


 -- CREATE TABLE "ASN"."IBMQREP_MCGSYNC"
 --  (
 --   MCGNAME VARCHAR2(64) NOT NULL ,
 --   REPQMAPNAME VARCHAR2(64) NOT NULL ,
 --   APPLY_SCHEMA VARCHAR2(30) NOT NULL ,
 --   UPDATE_TIME TIMESTAMP DEFAULT TIMESTAMP   '1900-01-01 00:00:00.000000',
 --   MAX_CMT_SEQ_READ RAW(16) DEFAULT HEXTORAW( 
 --'00000000000000000000000000000000' ) NOT NULL ,
 --   MAX_CMT_TIME_READ NUMBER(19) DEFAULT 0 NOT NULL ,
 --   OLDEST_TRANS NUMBER(19) DEFAULT 0 NOT NULL ,
 --   STATE CHARACTER(1) DEFAULT 'I' NOT NULL ,
 --   STATE_CHANGE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP,
 --   NUM_TRANS NUMBER(10) DEFAULT 0 NOT NULL ,
 --   NUM_MSGS NUMBER(10) DEFAULT 0 NOT NULL ,
 --   NEXT_APPLYUPTO_TIME NUMBER(19) DEFAULT 0 NOT NULL 
 --  );
 -- CREATE UNIQUE INDEX ASN.IX1MCGSYNC ON 
 --    "ASN"."IBMQREP_MCGSYNC"
 --  (
 --   MCGNAME,
 --   REPQMAPNAME,
 --   APPLY_SCHEMA
 --  );



 --  CREATE TABLE "ASN"."IBMQREP_MCGPARMS"
 --   (
 --    MCGNAME VARCHAR2(64) NOT NULL ,
 --    MCGSYNCINT NUMBER(10) DEFAULT 1000 NOT NULL ,
 --    MCGSYNCSTEP NUMBER(10) DEFAULT 0 NOT NULL 
 --   );
 --  CREATE UNIQUE INDEX ASN.IX1MCGPARMS ON 
 --     "ASN"."IBMQREP_MCGPARMS"
 --   (
 --    MCGNAME
 --   );


 --  CREATE TABLE !APPSCHEMA!.IBMQREP_MCGMON
 --   (
 --    MONITOR_TIME TIMESTAMP NOT NULL ,
 --    MCGNAME VARCHAR2(64) NOT NULL ,
 --    RECVQ VARCHAR2(48) NOT NULL ,
 --    MAX_CMT_SEQ_READ RAW(16) NOT NULL ,
 --    MAX_CMT_TIME_READ TIMESTAMP NOT NULL ,
 --    NUM_ACTIVE_CGS NUMBER(5) NOT NULL ,
 --    LOWEST_MCG_MAX_CMT_SEQ_READ RAW(16) NOT NULL ,
 --    LOWEST_MCG_OLDEST_TRANS TIMESTAMP NOT NULL ,
 --    NEXT_APPLYUPTO_TIME TIMESTAMP,
 --    NUM_TRANS_MCG_DELAY NUMBER(10) NOT NULL ,
 --    CURRENT_NUM_TRANS NUMBER(10) NOT NULL ,
 --    CURRENT_NUM_MSGS NUMBER(10) NOT NULL ,
 --    MCG_REFRESH_TIME TIMESTAMP NOT NULL ,
 --    IS_MOST_BEHIND CHARACTER(1) NOT NULL 
 --   );
 --  CREATE UNIQUE INDEX !APPSCHEMA!.IX1MCGMON 
 --     ON 
 --     !APPSCHEMA!.IBMQREP_MCGMON 
     
 --   (
 --    MONITOR_TIME ASC,
 --    RECVQ
 --   );



