--********************************************************************/
--                                                                   */
--          IBM InfoSphere Replication Server                         */
--      Version 10.2.1 for Linux, UNIX AND Windows                      */
--                                                                   */
--     Sample Q Replication migration script for UNIX AND NT         */
--     Licensed Materials - Property of IBM                          */
--                                                                   */
--     (C) Copyright IBM Corp. 1993, 2015. All Rights Reserved       */
--                                                                   */
--     US Government Users Restricted Rights - Use, duplication      */
--     or disclosure restricted by GSA ADP Schedule Contract         */
--     with IBM Corp.                                                */
--                                                                   */
--********************************************************************/
-- Script to migrate Teradata Q Apply control tables from V10 
-- or V105FP[1-6] to V10.5 FP7 or higher
-- Q Apply Migration script 
-- Prior to running this script, customize it to your existing 
-- Q Apply server environment:
-- (1) Locate and change all occurrences of the string 
--     !SERVER_NAME! to the name of the remote server as
--     defined to the federated database
-- (2) Locate and change the string !APPSCHEMA to schema of the Q Apply control
--     tables created in the Federated database.
-- (3) Locate and change the string !REMOTE_SCHEMA! to the schema
--     of the replication control tables created in the remote database
--(4) Locate and change all occurrences of the string !APPTS 
--    to the name of the tablespace where the Q Apply control tables 
--     are created


UPDATE !APPSCHEMA.IBMQREP_APPLYPARMS SET ARCH_LEVEL = '1021';
UPDATE !APPSCHEMA.IBMQREP_APPLYPARMS SET MULTI_ROW_INSERT = 'N';
ALTER TABLE !APPSCHEMA.IBMQREP_APPLYPARMS ADD COLUMN USE_APPLYCMD_TABLE CHAR(1) NOT NULL WITH DEFAULT 'N';
ALTER TABLE !APPSCHEMA.IBMQREP_APPLYPARMS ADD COLUMN APPLYCMD_INTERVAL INTEGER NOT NULL WITH DEFAULT 3000;

ALTER TABLE !APPSCHEMA.IBMQREP_APPLYMON  ADD COLUMN TRANS_READ INTEGER ;
ALTER TABLE !APPSCHEMA.IBMQREP_APPLYMON  ADD COLUMN  DEPENDENCY_DELAY INTEGER;
ALTER TABLE !APPSCHEMA.IBMQREP_APPLYMON  ADD COLUMN  MCGSYNC_DELAY INTEGER;
ALTER TABLE !APPSCHEMA.IBMQREP_APPLYMON  ADD COLUMN  WORKQ_WAIT_TIME INTEGER;
ALTER TABLE !APPSCHEMA.IBMQREP_APPLYMON  ADD COLUMN  RETRY_TIME INTEGER;
ALTER TABLE !APPSCHEMA.IBMQREP_APPLYMON  ADD COLUMN  DBMS_TIME INTEGER;
ALTER TABLE !APPSCHEMA.IBMQREP_APPLYMON  ADD COLUMN  STMTS_PREPARED INTEGER;
ALTER TABLE !APPSCHEMA.IBMQREP_APPLYMON  ADD COLUMN NUM_MRI_STMTS_EXECUTED INTEGER;
ALTER TABLE !APPSCHEMA.IBMQREP_APPLYMON  ADD COLUMN ROWS_PROCESSED_MRI INTEGER;
ALTER TABLE !APPSCHEMA.IBMQREP_APPLYMON  ADD COLUMN CURRENT_MEMORY_STMT_CACHE INTEGER;
ALTER TABLE !APPSCHEMA.IBMQREP_APPLYMON ADD COLUMN UNAVAIL_RES_RETRIES INTEGER NOT NULL WITH DEFAULT 0;



CREATE TABLE !APPSCHEMA.IBMQREP_APPEVTDEFS
(
 EVENTNAME VARCHAR(64) NOT NULL,
 QMAPNAME VARCHAR(64) NOT NULL,
 WORKLOADNAME VARCHAR(64) NOT NULL,
 TYPE VARCHAR(26) NOT NULL,
 EIF CHARACTER(1) NOT NULL WITH DEFAULT 'N',
 CONSOLE CHARACTER(1) NOT NULL WITH DEFAULT 'N',
 "TABLE" CHARACTER(1) NOT NULL WITH DEFAULT 'N',
 MAX INTEGER,
 RESET INTEGER,
 EIF_WORKLOADTYPE VARCHAR(18),
 PRIMARY KEY(QMAPNAME, WORKLOADNAME, TYPE)
)
 IN !APPTS;


CREATE TABLE !APPSCHEMA.IBMQREP_APPEVENTS
(
 EVENTTIME TIMESTAMP NOT NULL,
 WORKLOADNAME VARCHAR(64) NOT NULL,
 QMAPNAME VARCHAR(64) NOT NULL,
 TYPE VARCHAR(33) NOT NULL,
 THRESHOLD INTEGER,
 VALUE INTEGER,
 SYSPLEX CHARACTER(8),
 SYSTEM CHARACTER(8),
 JOBNAME CHARACTER(8),
 OLDEST_TRANS TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP
)
 IN !APPTS;


CREATE INDEX !APPSCHEMA.IX1APPEVENT ON !APPSCHEMA.IBMQREP_APPEVENTS
(
 EVENTTIME DESC
);

CREATE TABLE !APPSCHEMA.IBMQREP_APPLYCMD
(
 CMD_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 1
 INCREMENT BY 1 ),
 CMD_INPUT_TIME TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
 CMD_ORIGINATOR VARCHAR(128) NOT NULL WITH DEFAULT USER,
 CMD_TEXT VARCHAR(1024) NOT NULL,
 CMD_STATE CHARACTER(1) NOT NULL WITH DEFAULT 'P',
 CMD_RESULT_MSG VARCHAR(1024) WITH DEFAULT NULL,
 CMD_STATE_TIME TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
 CMD_RESULT_RC INTEGER WITH DEFAULT NULL
)
 IN !APPTS;


CREATE INDEX !APPSCHEMA.IX1APPLYCMD ON !APPSCHEMA.IBMQREP_APPLYCMD
(
 CMD_ID
);


;

-- Do not change the ASN schema for the following 2 tables
-- IBMQREP_MCGSYNC, IBMQREP_MCGPARMS

CREATE TABLE ASN.IBMQREP_MCGSYNC
( MCGNAME             VARCHAR(64)    NOT NULL,
REPQMAPNAME         VARCHAR(64)    NOT NULL ,
APPLY_SCHEMA        VARCHAR(30)    NOT  NULL,
UPDATE_TIME         TIMESTAMP DEFAULT '1900-01-01-00.00.00.000000',
MAX_CMT_SEQ_READ    VARCHAR(16) FOR BIT DATA NOT NULL
WITH DEFAULT X'00000000000000000000',
MAX_CMT_TIME_READ   BIGINT         NOT NULL DEFAULT 0,
OLDEST_TRANS        BIGINT         NOT NULL DEFAULT 0,
NEXT_APPLYUPTO_TIME BIGINT         NOT NULL DEFAULT 0,
NUM_TRANS           INT            NOT NULL DEFAULT 0,
NUM_MSGS            INT            NOT NULL DEFAULT 0,
STATE               CHAR(1)        NOT NULL DEFAULT ' ',
STATE_CHANGE_TIME   TIMESTAMP DEFAULT
)  IN !APPTS;

CREATE UNIQUE INDEX ASN.IX1MCGSYNC ON ASN.IBMQREP_MCGSYNC
( MCGNAME,  REPQMAPNAME,  APPLY_SCHEMA);


CREATE TABLE ASN.IBMQREP_MCGPARMS
( MCGNAME      VARCHAR(64) NOT NULL,
 MCGSYNCINT    INTEGER NOT NULL WITH DEFAULT 1000,
 MCGSYNCSTEP   INTEGER NOT NULL WITH DEFAULT 0
)  IN !APPTS;

CREATE UNIQUE INDEX ASN.IX1MCGPARMS ON ASN.IBMQREP_MCGPARMS
( MCGNAME);


CREATE BUFFERPOOL BP8K SIZE 125 PAGESIZE 8192;


CREATE TABLESPACE TSAPCMDOUT PAGESIZE 8192 MANAGED BY AUTOMATIC
 STORAGE BUFFERPOOL BP8K;


CREATE TABLE !APPSCHEMA.IBMQREP_APPLYCMDOUT
(
 CMD_ID BIGINT NOT NULL,
 CMD_SEQUENCE SMALLINT NOT NULL,
 CMD_OUTPUT VARCHAR(4000) NOT NULL
)
 IN TSAPCMDOUT;


CREATE INDEX !APPSCHEMA.IX1APPLYCMDOUT ON !APPSCHEMA.IBMQREP_APPLYCMDOUT
(
 CMD_ID,
 CMD_SEQUENCE
);

SET PASSTHRU !SERVER_NAME!;

ALTER TABLE !REMOTE_SCHEMA!.IBMQREP_RECVQUEUES ADD COLUMN MCGNAME VARCHAR(64) DEFAULT NULL;

ALTER TABLE !REMOTE_SCHEMA!.IBMQREP_RECVQUEUES ADD COLUMN AGENT_STMT_CACHE_SZ INTEGER NOT NULL WITH DEFAULT 300 ;

ALTER TABLE !REMOTE_SCHEMA!.IBMQREP_RECVQUEUES ADD COLUMN MRI_MEMORY_LIMIT INTEGER NOT NULL WITH DEFAULT 1024;

ALTER TABLE !REMOTE_SCHEMA!.IBMQREP_RECVQUEUES ADD BIDIAPPLY_SCHEMA VARCHAR2(128) DEFAULT NULL;


ALTER TABLE !REMOTE_SCHEMA!.IBMQREP_TARGETS ADD COLUMN REPL_DROP_COL CHAR(1) WITH DEFAULT 'Y';
ALTER TABLE !REMOTE_SCHEMA!.IBMQREP_TARGETS ADD COLUMN REPL_RENAME_COL CHAR(1) WITH DEFAULT 'Y';
ALTER TABLE !REMOTE_SCHEMA!.IBMQREP_TARGETS ADD COLUMN REPL_ALTER_COL CHAR(1) WITH DEFAULT 'Y';
ALTER TABLE !REMOTE_SCHEMA!.IBMQREP_TARGETS ADD COLUMN SRC_LOCATION_ALIAS VARCHAR(16) WITH DEFAULT NULL;

CREATE TABLE "!REMOTE_SCHEMA!"."IBMQREP_MCGMON"
(
 MONITOR_TIME TIMESTAMP NOT NULL ,
 MCGNAME VARCHAR(64) NOT NULL ,
 RECVQ VARCHAR(48) NOT NULL ,
 MAX_CMT_SEQ_READ BYTE NOT NULL ,
 MAX_CMT_TIME_READ TIMESTAMP NOT NULL ,
 NUM_ACTIVE_CGS SMALLINT NOT NULL ,
 LOWEST_MCG_MAX_CMT_SEQ_READ BYTE NOT NULL ,
 LOWEST_MCG_OLDEST_TRANS TIMESTAMP NOT NULL ,
 NEXT_APPLYUPTO_TIME TIMESTAMP ,
 NUM_TRANS_MCG_DELAY INTEGER NOT NULL ,
 CURRENT_NUM_TRANS INTEGER NOT NULL ,
 CURRENT_NUM_MSGS INTEGER NOT NULL ,
 MCG_REFRESH_TIME TIMESTAMP NOT NULL ,
 IS_MOST_BEHIND CHARACTER(1) NOT NULL 
);


CREATE UNIQUE INDEX "!REMOTE_SCHEMA!"."IX1MCGMON" ON "!REMOTE_SCHEMA!"."IBMQREP_MCGMON"
(
 MONITOR_TIME,
 RECVQ
);
SET PASSTHRU RESET;

CREATE NICKNAME !APPSCHEMA.IBMQREP_MCGMON FOR
 !SERVER_NAME!."!REMOTE_SCHEMA!"."IBMQREP_MCGMON";
