--# Copyright IBM Corp. All Rights Reserved.
--# SPDX-License-Identifier: Apache-2.0

/*
 * Example code that stores the dynamic result sets from AUTOCONFIGURE APPLY NONE when called from ADMIN_CMD 
 */

DROP  TABLE IF EXISTS DB_AUTOCONFIGURE_RESULT1
@

CREATE TABLE DB_AUTOCONFIGURE_RESULT1 (
    LEVEL               VARCHAR(3)   NOT NULL
,   NAME                VARCHAR(128) NOT NULL
,   VALUE               VARCHAR(256) NOT NULL
,   RECOMMENDED_VALUE   VARCHAR(256) NOT NULL
,   DATATYPE            VARCHAR(128) NOT NULL
,   MEMBER              INTEGER      
--,   PRIMARY KEY (MEMBER, NAME) ENFORCED
)
@
BEGIN
    DECLARE SQLSTATE CHAR(5);
    DECLARE V_LEVEL               VARCHAR(3)  ;
    DECLARE V_NAME                VARCHAR(128);
    DECLARE V_VALUE               VARCHAR(256);
    DECLARE V_RECOMMENDED_VALUE   VARCHAR(256);
    DECLARE V_DATATYPE            VARCHAR(128);
    DECLARE V_MEMBER              INTEGER     ;
    DECLARE V1 RESULT_SET_LOCATOR VARYING;
    --
    CALL SYSPROC.ADMIN_CMD('AUTOCONFIGURE
        USING
            MEM_PERCENT 80
        APPLY NONE
        REPORT FOR MEMBER -2
        '); -- enter your custom autoconfig settings if needed
    ASSOCIATE RESULT SET LOCATOR (V1 ) WITH PROCEDURE SYSPROC.ADMIN_CMD;
    ALLOCATE C1 CURSOR FOR RESULT SET V1;
    --
    L1: LOOP
        FETCH C1                                 INTO V_LEVEL, V_NAME, V_VALUE, V_RECOMMENDED_VALUE, V_DATATYPE, V_MEMBER ;
        IF SQLSTATE<>'00000' THEN LEAVE L1; END IF;        
        INSERT INTO DB_AUTOCONFIGURE_RESULT1 VALUES ( V_LEVEL, V_NAME, V_VALUE, V_RECOMMENDED_VALUE, V_DATATYPE, V_MEMBER);
    END LOOP L1;
    CLOSE C1;
    --
END
@
SELECT
    LEVEL
,   NAME
,   VALUE
,   RECOMMENDED_VALUE
,   LISTAGG(COALESCE(VARCHAR(MEMBER),''), ',') WITHIN GROUP (ORDER BY MEMBER) AS MEMBERS
FROM
    DB_AUTOCONFIGURE_RESULT1 
GROUP BY
    LEVEL
, NAME
,   VALUE
,   RECOMMENDED_VALUE
ORDER BY
    CASE LEVEL WHEN 'DBM' THEN 1 WHEN 'BP' THEN 2 WHEN 'DB' THEN 4 WHEN 'WLM' THEN 5 END
,   NAME
@
 