--# Copyright IBM Corp. All Rights Reserved.
--# SPDX-License-Identifier: Apache-2.0

/*
 * Run the SQL generated by the DB_COLUMN_REDESIGN view generated SQL for a set of tables
 * 
 * This will populate the DBT_COLUMN_REDESIGN table with information about the data held by each column
 * 
 * This table can then be used to generate "improved" DDL for a table
 * 
 * This is intended to be similar to what nz_ddl_table_redesign does
 * 
 * Still a work in progress * Need to add a table DDL generator based on the table below
 * 
 */

--DELETE FROM DBT_COLUMN_REDESIGN
--DROP TABLE DBT_COLUMN_REDESIGN

CREATE TABLE DBT_COLUMN_REDESIGN
(
    TABSCHEMA         VARCHAR(128 OCTETS) NOT NULL
,   TABNAME           VARCHAR(128 OCTETS) NOT NULL
,   COLNAME           VARCHAR(128 OCTETS) NOT NULL
,   COLNO             SMALLINT            NOT NULL
,   TYPESCHEMA        VARCHAR(128 OCTETS) NOT NULL
,   TYPENAME          VARCHAR(128 OCTETS) NOT NULL
,   LENGTH            INTEGER             NOT NULL
,   SCALE             SMALLINT            NOT NULL
,   TYPESTRINGUNITS   VARCHAR(11 OCTETS)
,   STRINGUNITSLENGTH INTEGER
,   NULLS             CHAR(1)        NOT NULL
,   CODEPAGE          SMALLINT       NOT NULL
,   ROW_COUNT         BIGINT NOT NULL
,   DISTINCT_COUNT    BIGINT
,   NULL_COUNT        BIGINT NOT NULL
,   MAX_VALUE         VARCHAR(4096)
,   MIN_VALUE         VARCHAR(4096)
,   AVG_VALUE         VARCHAR(4096)
,   MAX_LENGTH        INTEGER
,   MAX_LENGTH4       INTEGER
,   MIN_LENGTH        INTEGER
,   AVG_LENGTH        INTEGER
,   MAX_SCALE         SMALLINT
,   ONLY_DIGITS_COUNT   BIGINT
)

@

BEGIN
    FOR C AS cur CURSOR WITH HOLD FOR
        SELECT 'INSERT INTO DBT_COLUMN_REDESIGN' || CHR(10) || SELECT_STMT  AS S
        FROM
            DB_COLUMN_REDESIGN  JOIN SYSCAT.TABLES USING ( TABSCHEMA, TABNAME )
        WHERE TABSCHEMA = 'your schema'
        AND TABNAME = 'your table'
--        AND   CARD BETWEEN 1 AND 200000000  -- ignore tables with > 200 million rows
        AND    ( TABSCHEMA, TABNAME, COLNAME ) NOT IN (SELECT TABSCHEMA, TABNAME, COLNAME FROM DBT_COLUMN_REDESIGN )
        ORDER BY TABSCHEMA, TABNAME, COLNO
        WITH UR
    DO
          EXECUTE IMMEDIATE C.S;
          COMMIT;
    END FOR;
END
@
