--# Copyright IBM Corp. All Rights Reserved.
--# SPDX-License-Identifier: Apache-2.0

/*
 * Export system catalog views to your client
 * 
 * These can then be loaded to another Db2 instance to allow "off-line" analysis of the database,
 *     including using the "snapshot" version of the db-lib against this data
 * 
 * Note that external tables don't currently support any column data longer than 64K bytes.
 * So the code below truncates any such columns
 * 
 * If on Db2 11.5.2.0 or above, use the BINARY data transfer option
 * 
 * Also, as REMOTESOURCE external tables are not supported in compound statements
 * Below is the generated code
*/

CREATE EXTERNAL TABLE '/home/paul/git/db2_catalog_backup/SYSCAT.BUFFERPOOLS.dat.lz4'             USING ( REMOTESOURCE YES FORMAT BINARY COMPRESS LZ4) AS SELECT "BPNAME","BUFFERPOOLID","DBPGNAME","NPAGES","PAGESIZE","ESTORE","NUMBLOCKPAGES","BLOCKSIZE","NGNAME" FROM "SYSCAT  "."BUFFERPOOLS"@
CREATE EXTERNAL TABLE '/home/paul/git/db2_catalog_backup/SYSCAT.COLGROUPCOLS.dat.lz4'            USING ( REMOTESOURCE YES FORMAT BINARY COMPRESS LZ4) AS SELECT "COLGROUPID","COLNAME","TABSCHEMA","TABNAME","ORDINAL" FROM "SYSCAT  "."COLGROUPCOLS"@
CREATE EXTERNAL TABLE '/home/paul/git/db2_catalog_backup/SYSCAT.COLGROUPS.dat.lz4'               USING ( REMOTESOURCE YES FORMAT BINARY COMPRESS LZ4) AS SELECT "COLGROUPSCHEMA","COLGROUPNAME","COLGROUPID","COLGROUPCARD","NUMFREQ_VALUES","NUMQUANTILES" FROM "SYSCAT  "."COLGROUPS"@
CREATE EXTERNAL TABLE '/home/paul/git/db2_catalog_backup/SYSCAT.COLUMNS.dat.lz4'                 USING ( REMOTESOURCE YES FORMAT BINARY COMPRESS LZ4) AS SELECT "TABSCHEMA","TABNAME","COLNAME","COLNO","TYPESCHEMA","TYPENAME","LENGTH","SCALE","TYPESTRINGUNITS","STRINGUNITSLENGTH",CLOB("DEFAULT",65535),"NULLS","CODEPAGE","COLLATIONSCHEMA","COLLATIONNAME","LOGGED","COMPACT","COLCARD","HIGH2KEY","LOW2KEY","AVGCOLLEN","KEYSEQ","PARTKEYSEQ","NQUANTILES","NMOSTFREQ","NUMNULLS","TARGET_TYPESCHEMA","TARGET_TYPENAME","SCOPE_TABSCHEMA","SCOPE_TABNAME","SOURCE_TABSCHEMA","SOURCE_TABNAME","DL_FEATURES","SPECIAL_PROPS","HIDDEN","INLINE_LENGTH","PCTINLINED","IDENTITY","ROWCHANGETIMESTAMP","GENERATED",CLOB("TEXT",65535),"COMPRESS","AVGDISTINCTPERPAGE","PAGEVARIANCERATIO","SUB_COUNT","SUB_DELIM_LENGTH","AVGCOLLENCHAR","IMPLICITVALUE","SECLABELNAME","ROWBEGIN","ROWEND","TRANSACTIONSTARTID","PCTENCODED","AVGENCODEDCOLLEN","QUALIFIER",CLOB("FUNC_PATH",65535),"RANDDISTKEY","REMARKS" FROM "SYSCAT  "."COLUMNS"@
CREATE EXTERNAL TABLE '/home/paul/git/db2_catalog_backup/SYSCAT.INDEXCOLUSE.dat.lz4'             USING ( REMOTESOURCE YES FORMAT BINARY COMPRESS LZ4) AS SELECT "INDSCHEMA","INDNAME","COLNAME","COLSEQ","COLORDER","COLLATIONSCHEMA","COLLATIONNAME","VIRTUAL",CLOB("TEXT",65535) FROM "SYSCAT  "."INDEXCOLUSE"@
CREATE EXTERNAL TABLE '/home/paul/git/db2_catalog_backup/SYSCAT.INDEXES.dat.lz4'                 USING ( REMOTESOURCE YES FORMAT BINARY COMPRESS LZ4) AS SELECT "INDSCHEMA","INDNAME","OWNER","OWNERTYPE","TABSCHEMA","TABNAME","COLNAMES","UNIQUERULE","MADE_UNIQUE","COLCOUNT","UNIQUE_COLCOUNT","INDEXTYPE","ENTRYTYPE","PCTFREE","IID","NLEAF","NLEVELS","FIRSTKEYCARD","FIRST2KEYCARD","FIRST3KEYCARD","FIRST4KEYCARD","FULLKEYCARD","CLUSTERRATIO","CLUSTERFACTOR","SEQUENTIAL_PAGES","DENSITY","USER_DEFINED","SYSTEM_REQUIRED","CREATE_TIME","STATS_TIME","PAGE_FETCH_PAIRS","MINPCTUSED","REVERSE_SCANS","INTERNAL_FORMAT","COMPRESSION","IESCHEMA","IENAME",CLOB("IEARGUMENTS",65535),"INDEX_OBJECTID","NUMRIDS","NUMRIDS_DELETED","NUM_EMPTY_LEAFS","AVERAGE_RANDOM_FETCH_PAGES","AVERAGE_RANDOM_PAGES","AVERAGE_SEQUENCE_GAP","AVERAGE_SEQUENCE_FETCH_GAP","AVERAGE_SEQUENCE_PAGES","AVERAGE_SEQUENCE_FETCH_PAGES","TBSPACEID","LEVEL2PCTFREE","PAGESPLIT","AVGPARTITION_CLUSTERRATIO","AVGPARTITION_CLUSTERFACTOR","AVGPARTITION_PAGE_FETCH_PAIRS","PCTPAGESSAVED","DATAPARTITION_CLUSTERFACTOR","INDCARD","AVGLEAFKEYSIZE","AVGNLEAFKEYSIZE","OS_PTR_SIZE","COLLECTSTATISTCS","DEFINER","LASTUSED","PERIODNAME","PERIODPOLICY","MADE_WITHOUTOVERLAPS","ENVSTRINGUNITS","NULLKEYS",CLOB("FUNC_PATH",65535),"VIEWSCHEMA","VIEWNAME","REMARKS" FROM "SYSCAT  "."INDEXES"@
CREATE EXTERNAL TABLE '/home/paul/git/db2_catalog_backup/SYSCAT.KEYCOLUSE.dat.lz4'               USING ( REMOTESOURCE YES FORMAT BINARY COMPRESS LZ4) AS SELECT "CONSTNAME","TABSCHEMA","TABNAME","COLNAME","COLSEQ" FROM "SYSCAT  "."KEYCOLUSE"@
CREATE EXTERNAL TABLE '/home/paul/git/db2_catalog_backup/SYSCAT.TABCONST.dat.lz4'                USING ( REMOTESOURCE YES FORMAT BINARY COMPRESS LZ4) AS SELECT "CONSTNAME","TABSCHEMA","TABNAME","OWNER","OWNERTYPE","TYPE","ENFORCED","TRUSTED","CHECKEXISTINGDATA","ENABLEQUERYOPT","DEFINER","PERIODNAME","PERIODPOLICY","REMARKS" FROM "SYSCAT  "."TABCONST"@
CREATE EXTERNAL TABLE '/home/paul/git/db2_catalog_backup/SYSCAT.TABDEP.dat.lz4'                  USING ( REMOTESOURCE YES FORMAT BINARY COMPRESS LZ4) AS SELECT "TABSCHEMA","TABNAME","DTYPE","OWNER","OWNERTYPE","BTYPE","BSCHEMA","BMODULENAME","BNAME","BMODULEID","TABAUTH","VARAUTH","DEFINER" FROM "SYSCAT  "."TABDEP"@
CREATE EXTERNAL TABLE '/home/paul/git/db2_catalog_backup/SYSCAT.TABLES.dat.lz4'                  USING ( REMOTESOURCE YES FORMAT BINARY COMPRESS LZ4) AS SELECT "TABSCHEMA","TABNAME","OWNER","OWNERTYPE","TYPE","STATUS","BASE_TABSCHEMA","BASE_TABNAME","ROWTYPESCHEMA","ROWTYPENAME","CREATE_TIME","ALTER_TIME","INVALIDATE_TIME","STATS_TIME","COLCOUNT","TABLEID","TBSPACEID","CARD","NPAGES","MPAGES","FPAGES","NPARTITIONS","NFILES","TABLESIZE","OVERFLOW","TBSPACE","INDEX_TBSPACE","LONG_TBSPACE","PARENTS","CHILDREN","SELFREFS","KEYCOLUMNS","KEYINDEXID","KEYUNIQUE","CHECKCOUNT","DATACAPTURE","CONST_CHECKED","PMAP_ID","PARTITION_MODE","LOG_ATTRIBUTE","PCTFREE","APPEND_MODE","REFRESH","REFRESH_TIME","LOCKSIZE","VOLATILE","ROW_FORMAT","PROPERTY",CLOB("STATISTICS_PROFILE",65535),"COMPRESSION","ROWCOMPMODE","ACCESS_MODE","CLUSTERED","ACTIVE_BLOCKS","DROPRULE","MAXFREESPACESEARCH","AVGCOMPRESSEDROWSIZE","AVGROWCOMPRESSIONRATIO","AVGROWSIZE","PCTROWSCOMPRESSED","LOGINDEXBUILD","CODEPAGE","COLLATIONSCHEMA","COLLATIONNAME","COLLATIONSCHEMA_ORDERBY","COLLATIONNAME_ORDERBY","ENCODING_SCHEME","PCTPAGESSAVED","LAST_REGEN_TIME","SECPOLICYID","PROTECTIONGRANULARITY","AUDITPOLICYID","AUDITPOLICYNAME","AUDITEXCEPTIONENABLED","DEFINER","ONCOMMIT","LOGGED","ONROLLBACK","LASTUSED","CONTROL","TEMPORALTYPE","TABLEORG","EXTENDED_ROW_SIZE","PCTEXTENDEDROWS","REMARKS" FROM "SYSCAT  "."TABLES"@
CREATE EXTERNAL TABLE '/home/paul/git/db2_catalog_backup/SYSCAT.TABLESPACES.dat.lz4'             USING ( REMOTESOURCE YES FORMAT BINARY COMPRESS LZ4) AS SELECT "TBSPACE","OWNER","OWNERTYPE","CREATE_TIME","TBSPACEID","TBSPACETYPE","DATATYPE","EXTENTSIZE","PREFETCHSIZE","OVERHEAD","TRANSFERRATE","WRITEOVERHEAD","WRITETRANSFERRATE","PAGESIZE","DBPGNAME","BUFFERPOOLID","DROP_RECOVERY","NGNAME","DEFINER","DATATAG","SGNAME","SGID","EFFECTIVEPREFETCHSIZE","CACHINGTIER","REMARKS" FROM "SYSCAT  "."TABLESPACES"@
CREATE EXTERNAL TABLE '/home/paul/git/db2_catalog_backup/SYSCAT.THRESHOLDS.dat.lz4'              USING ( REMOTESOURCE YES FORMAT BINARY COMPRESS LZ4) AS SELECT "THRESHOLDNAME","THRESHOLDID","ORIGIN","THRESHOLDCLASS","THRESHOLDPREDICATE","THRESHOLDPREDICATEID","DOMAIN","DOMAINID","ENFORCEMENT","QUEUING","MAXVALUE","DATATAGLIST","QUEUESIZE","OVERFLOWPERCENT","COLLECTACTDATA","COLLECTACTPARTITION","EXECUTION","REMAPSCID","VIOLATIONRECORDLOGGED","CHECKINTERVAL","ENABLED","CREATE_TIME","ALTER_TIME","REMARKS" FROM "SYSCAT  "."THRESHOLDS"@
CREATE EXTERNAL TABLE '/home/paul/git/db2_catalog_backup/SYSCAT.VIEWDEP.dat.lz4'                 USING ( REMOTESOURCE YES FORMAT BINARY COMPRESS LZ4) AS SELECT "VIEWSCHEMA","VIEWNAME","DTYPE","OWNER","BTYPE","BSCHEMA","BMODULENAME","BNAME","BMODULEID","TABAUTH","DEFINER" FROM "SYSCAT  "."VIEWDEP"@
CREATE EXTERNAL TABLE '/home/paul/git/db2_catalog_backup/SYSCAT.VIEWS.dat.lz4'                   USING ( REMOTESOURCE YES FORMAT BINARY COMPRESS LZ4) AS SELECT "VIEWSCHEMA","VIEWNAME","OWNER","OWNERTYPE","SEQNO","VIEWCHECK","READONLY","VALID","QUALIFIER",CLOB("FUNC_PATH",65535),CLOB("TEXT",65535),"DEFINER","ENVSTRINGUNITS" FROM "SYSCAT  "."VIEWS"@
CREATE EXTERNAL TABLE '/home/paul/git/db2_catalog_backup/SYSCAT.WORKCLASSATTRIBUTES.dat.lz4'     USING ( REMOTESOURCE YES FORMAT BINARY COMPRESS LZ4) AS SELECT "WORKCLASSNAME","WORKCLASSSETNAME","WORKCLASSID","WORKCLASSSETID","TYPE","VALUE1","VALUE2","VALUE3" FROM "SYSCAT  "."WORKCLASSATTRIBUTES"@

-- Code Generator for the above
SELECT
    'CREATE EXTERNAL TABLE ''/home/paul/git/db2_catalog_backup/' || RTRIM(TABSCHEMA) || '.' || TABNAME 
    || '.dat.lz4'''
--        || '.csv.gz'''
    || REPEAT(' ',(MAX(0,30 - LENGTH(RTRIM(TABSCHEMA) || '.' || TABNAME))))
    || ' USING ( REMOTESOURCE YES'
    ||  ' FORMAT BINARY COMPRESS LZ4' 
--        ||  CHR(10) ||  ' FORMAT TEXT CCSID 1208 ESCAPECHAR ''~'' CTRLCHARS TRUE COMPRESS GZIP'
    || ') AS SELECT '
        || LISTAGG(
               CASE WHEN TYPENAME IN ('BLOB','CLOB','DCLOB') THEN TYPENAME || '(' || '"' || COLNAME || '"'       
                 || CASE TYPESTRINGUNITS WHEN 'CODEUNITS32' THEN ',16383' 
                                         WHEN 'CODEUNITS16' THEN ',32767'
                                                            ELSE ',65535' END || ')'
             ELSE '"' || COLNAME || '"' END
            ,',') WITHIN GROUP ( ORDER BY COLNO)  
    || ' FROM'
    || ' "' || TABSCHEMA || '"."' || TABNAME || '"'
    || '@' AS STMT
FROM
    SYSCAT.COLUMNS JOIN SYSCAT.TABLES USING (TABSCHEMA, TABNAME)
WHERE
    TABSCHEMA = 'SYSCAT'
AND TABNAME IN 
    ('TABLES', 'COLUMNS', 'VIEWS', 'INDEXES', 'INDEXCOLUSE', 'TABLESPACES', 'TABDEP', 'VIEWDEP', 'KEYCOLUSE', 'TABCONST', 'THRESHOLDS'
    , 'WORKCLASSATTRIBUTES', 'DBPARTITONGROUPDEF', 'COLGROUPS', 'COLGROUPCOLS', 'BUFFERPOOLS')
GROUP BY
    TABSCHEMA
,   TABNAME
ORDER BY
        TABSCHEMA
    ,   TABNAME
WITH UR
