DROP   TABLE MON_GET_PKG_CACHE_STMT
@
CREATE TABLE MON_GET_PKG_CACHE_STMT
(
    "MEMBER"                                  SMALLINT
,   "SECTION_TYPE"                            CHAR(1 OCTETS)
,   "INSERT_TIMESTAMP"                        TIMESTAMP
,   "EXECUTABLE_ID"                           VARCHAR(32) FOR BIT DATA
,   "PACKAGE_SCHEMA"                          VARCHAR(128 OCTETS)
,   "PACKAGE_NAME"                            VARCHAR(128 OCTETS)
,   "PACKAGE_VERSION_ID"                      VARCHAR(64 OCTETS)
,   "SECTION_NUMBER"                          BIGINT
,   "EFFECTIVE_ISOLATION"                     CHAR(2 OCTETS)
,   "NUM_EXECUTIONS"                          BIGINT
,   "NUM_EXEC_WITH_METRICS"                   BIGINT
,   "PREP_TIME"                               BIGINT
,   "TOTAL_ACT_TIME"                          BIGINT
,   "TOTAL_ACT_WAIT_TIME"                     BIGINT
,   "TOTAL_CPU_TIME"                          BIGINT
,   "POOL_READ_TIME"                          BIGINT
,   "POOL_WRITE_TIME"                         BIGINT
,   "DIRECT_READ_TIME"                        BIGINT
,   "DIRECT_WRITE_TIME"                       BIGINT
,   "LOCK_WAIT_TIME"                          BIGINT
,   "TOTAL_SECTION_SORT_TIME"                 BIGINT
,   "TOTAL_SECTION_SORT_PROC_TIME"            BIGINT
,   "TOTAL_SECTION_SORTS"                     BIGINT
,   "LOCK_ESCALS"                             BIGINT
,   "LOCK_WAITS"                              BIGINT
,   "ROWS_MODIFIED"                           BIGINT
,   "ROWS_READ"                               BIGINT
,   "ROWS_RETURNED"                           BIGINT
,   "DIRECT_READS"                            BIGINT
,   "DIRECT_READ_REQS"                        BIGINT
,   "DIRECT_WRITES"                           BIGINT
,   "DIRECT_WRITE_REQS"                       BIGINT
,   "POOL_DATA_L_READS"                       BIGINT
,   "POOL_TEMP_DATA_L_READS"                  BIGINT
,   "POOL_XDA_L_READS"                        BIGINT
,   "POOL_TEMP_XDA_L_READS"                   BIGINT
,   "POOL_INDEX_L_READS"                      BIGINT
,   "POOL_TEMP_INDEX_L_READS"                 BIGINT
,   "POOL_DATA_P_READS"                       BIGINT
,   "POOL_TEMP_DATA_P_READS"                  BIGINT
,   "POOL_XDA_P_READS"                        BIGINT
,   "POOL_TEMP_XDA_P_READS"                   BIGINT
,   "POOL_INDEX_P_READS"                      BIGINT
,   "POOL_TEMP_INDEX_P_READS"                 BIGINT
,   "POOL_DATA_WRITES"                        BIGINT
,   "POOL_XDA_WRITES"                         BIGINT
,   "POOL_INDEX_WRITES"                       BIGINT
,   "TOTAL_SORTS"                             BIGINT
,   "POST_THRESHOLD_SORTS"                    BIGINT
,   "POST_SHRTHRESHOLD_SORTS"                 BIGINT
,   "SORT_OVERFLOWS"                          BIGINT
,   "WLM_QUEUE_TIME_TOTAL"                    BIGINT
,   "WLM_QUEUE_ASSIGNMENTS_TOTAL"             BIGINT
,   "DEADLOCKS"                               BIGINT
,   "FCM_RECV_VOLUME"                         BIGINT
,   "FCM_RECVS_TOTAL"                         BIGINT
,   "FCM_SEND_VOLUME"                         BIGINT
,   "FCM_SENDS_TOTAL"                         BIGINT
,   "FCM_RECV_WAIT_TIME"                      BIGINT
,   "FCM_SEND_WAIT_TIME"                      BIGINT
,   "LOCK_TIMEOUTS"                           BIGINT
,   "LOG_BUFFER_WAIT_TIME"                    BIGINT
,   "NUM_LOG_BUFFER_FULL"                     BIGINT
,   "LOG_DISK_WAIT_TIME"                      BIGINT
,   "LOG_DISK_WAITS_TOTAL"                    BIGINT
,   "LAST_METRICS_UPDATE"                     TIMESTAMP
,   "NUM_COORD_EXEC"                          BIGINT
,   "NUM_COORD_EXEC_WITH_METRICS"             BIGINT
,   "VALID"                                   CHAR(1 OCTETS)
,   "TOTAL_ROUTINE_TIME"                      BIGINT
,   "TOTAL_ROUTINE_INVOCATIONS"               BIGINT
,   "ROUTINE_ID"                              BIGINT
,   "STMT_TYPE_ID"                            VARCHAR(32 OCTETS)
,   "QUERY_COST_ESTIMATE"                     BIGINT
,   "STMT_PKG_CACHE_ID"                       BIGINT
,   "COORD_STMT_EXEC_TIME"                    BIGINT
,   "STMT_EXEC_TIME"                          BIGINT
,   "TOTAL_SECTION_TIME"                      BIGINT
,   "TOTAL_SECTION_PROC_TIME"                 BIGINT
,   "TOTAL_ROUTINE_NON_SECT_TIME"             BIGINT
,   "TOTAL_ROUTINE_NON_SECT_PROC_TIME"        BIGINT
,   "LOCK_WAITS_GLOBAL"                       BIGINT
,   "LOCK_WAIT_TIME_GLOBAL"                   BIGINT
,   "LOCK_TIMEOUTS_GLOBAL"                    BIGINT
,   "LOCK_ESCALS_MAXLOCKS"                    BIGINT
,   "LOCK_ESCALS_LOCKLIST"                    BIGINT
,   "LOCK_ESCALS_GLOBAL"                      BIGINT
,   "RECLAIM_WAIT_TIME"                       BIGINT
,   "SPACEMAPPAGE_RECLAIM_WAIT_TIME"          BIGINT
,   "CF_WAITS"                                BIGINT
,   "CF_WAIT_TIME"                            BIGINT
,   "POOL_DATA_GBP_L_READS"                   BIGINT
,   "POOL_DATA_GBP_P_READS"                   BIGINT
,   "POOL_DATA_LBP_PAGES_FOUND"               BIGINT
,   "POOL_DATA_GBP_INVALID_PAGES"             BIGINT
,   "POOL_INDEX_GBP_L_READS"                  BIGINT
,   "POOL_INDEX_GBP_P_READS"                  BIGINT
,   "POOL_INDEX_LBP_PAGES_FOUND"              BIGINT
,   "POOL_INDEX_GBP_INVALID_PAGES"            BIGINT
,   "POOL_XDA_GBP_L_READS"                    BIGINT
,   "POOL_XDA_GBP_P_READS"                    BIGINT
,   "POOL_XDA_LBP_PAGES_FOUND"                BIGINT
,   "POOL_XDA_GBP_INVALID_PAGES"              BIGINT
,   "AUDIT_EVENTS_TOTAL"                      BIGINT
,   "AUDIT_FILE_WRITES_TOTAL"                 BIGINT
,   "AUDIT_FILE_WRITE_WAIT_TIME"              BIGINT
,   "AUDIT_SUBSYSTEM_WAITS_TOTAL"             BIGINT
,   "AUDIT_SUBSYSTEM_WAIT_TIME"               BIGINT
,   "DIAGLOG_WRITES_TOTAL"                    BIGINT
,   "DIAGLOG_WRITE_WAIT_TIME"                 BIGINT
,   "FCM_MESSAGE_RECVS_TOTAL"                 BIGINT
,   "FCM_MESSAGE_RECV_VOLUME"                 BIGINT
,   "FCM_MESSAGE_RECV_WAIT_TIME"              BIGINT
,   "FCM_MESSAGE_SENDS_TOTAL"                 BIGINT
,   "FCM_MESSAGE_SEND_VOLUME"                 BIGINT
,   "FCM_MESSAGE_SEND_WAIT_TIME"              BIGINT
,   "FCM_TQ_RECVS_TOTAL"                      BIGINT
,   "FCM_TQ_RECV_VOLUME"                      BIGINT
,   "FCM_TQ_RECV_WAIT_TIME"                   BIGINT
,   "FCM_TQ_SENDS_TOTAL"                      BIGINT
,   "FCM_TQ_SEND_VOLUME"                      BIGINT
,   "FCM_TQ_SEND_WAIT_TIME"                   BIGINT
,   "NUM_LW_THRESH_EXCEEDED"                  BIGINT
,   "THRESH_VIOLATIONS"                       BIGINT
,   "TOTAL_APP_SECTION_EXECUTIONS"            BIGINT
,   "TOTAL_ROUTINE_USER_CODE_PROC_TIME"       BIGINT
,   "TOTAL_ROUTINE_USER_CODE_TIME"            BIGINT
,   "TQ_TOT_SEND_SPILLS"                      BIGINT
,   "EVMON_WAIT_TIME"                         BIGINT
,   "EVMON_WAITS_TOTAL"                       BIGINT
,   "TOTAL_EXTENDED_LATCH_WAIT_TIME"          BIGINT
,   "TOTAL_EXTENDED_LATCH_WAITS"              BIGINT
,   "MAX_COORD_STMT_EXEC_TIME"                BIGINT
,   "MAX_COORD_STMT_EXEC_TIMESTAMP"           TIMESTAMP
,   "TOTAL_DISP_RUN_QUEUE_TIME"               BIGINT
,   "QUERY_DATA_TAG_LIST"                     VARCHAR(32 OCTETS)
,   "TOTAL_STATS_FABRICATION_TIME"            BIGINT
,   "TOTAL_STATS_FABRICATIONS"                BIGINT
,   "TOTAL_SYNC_RUNSTATS_TIME"                BIGINT
,   "TOTAL_SYNC_RUNSTATS"                     BIGINT
,   "TOTAL_PEDS"                              BIGINT
,   "DISABLED_PEDS"                           BIGINT
,   "POST_THRESHOLD_PEDS"                     BIGINT
,   "TOTAL_PEAS"                              BIGINT
,   "POST_THRESHOLD_PEAS"                     BIGINT
,   "TQ_SORT_HEAP_REQUESTS"                   BIGINT
,   "TQ_SORT_HEAP_REJECTIONS"                 BIGINT
,   "POOL_QUEUED_ASYNC_DATA_REQS"             BIGINT
,   "POOL_QUEUED_ASYNC_INDEX_REQS"            BIGINT
,   "POOL_QUEUED_ASYNC_XDA_REQS"              BIGINT
,   "POOL_QUEUED_ASYNC_TEMP_DATA_REQS"        BIGINT
,   "POOL_QUEUED_ASYNC_TEMP_INDEX_REQS"       BIGINT
,   "POOL_QUEUED_ASYNC_TEMP_XDA_REQS"         BIGINT
,   "POOL_QUEUED_ASYNC_OTHER_REQS"            BIGINT
,   "POOL_QUEUED_ASYNC_DATA_PAGES"            BIGINT
,   "POOL_QUEUED_ASYNC_INDEX_PAGES"           BIGINT
,   "POOL_QUEUED_ASYNC_XDA_PAGES"             BIGINT
,   "POOL_QUEUED_ASYNC_TEMP_DATA_PAGES"       BIGINT
,   "POOL_QUEUED_ASYNC_TEMP_INDEX_PAGES"      BIGINT
,   "POOL_QUEUED_ASYNC_TEMP_XDA_PAGES"        BIGINT
,   "POOL_FAILED_ASYNC_DATA_REQS"             BIGINT
,   "POOL_FAILED_ASYNC_INDEX_REQS"            BIGINT
,   "POOL_FAILED_ASYNC_XDA_REQS"              BIGINT
,   "POOL_FAILED_ASYNC_TEMP_DATA_REQS"        BIGINT
,   "POOL_FAILED_ASYNC_TEMP_INDEX_REQS"       BIGINT
,   "POOL_FAILED_ASYNC_TEMP_XDA_REQS"         BIGINT
,   "POOL_FAILED_ASYNC_OTHER_REQS"            BIGINT
,   "PREFETCH_WAIT_TIME"                      BIGINT
,   "PREFETCH_WAITS"                          BIGINT
,   "POOL_DATA_GBP_INDEP_PAGES_FOUND_IN_LBP"  BIGINT
,   "POOL_INDEX_GBP_INDEP_PAGES_FOUND_IN_LBP" BIGINT
,   "POOL_XDA_GBP_INDEP_PAGES_FOUND_IN_LBP"   BIGINT
,   "NUM_WORKING_COPIES"                      BIGINT
,   "IDA_SEND_WAIT_TIME"                      BIGINT
,   "IDA_SENDS_TOTAL"                         BIGINT
,   "IDA_SEND_VOLUME"                         BIGINT
,   "IDA_RECV_WAIT_TIME"                      BIGINT
,   "IDA_RECVS_TOTAL"                         BIGINT
,   "IDA_RECV_VOLUME"                         BIGINT
,   "STMTNO"                                  INTEGER
,   "NUM_ROUTINES"                            INTEGER
,   "ROWS_DELETED"                            BIGINT
,   "ROWS_INSERTED"                           BIGINT
,   "ROWS_UPDATED"                            BIGINT
,   "TOTAL_HASH_JOINS"                        BIGINT
,   "TOTAL_HASH_LOOPS"                        BIGINT
,   "HASH_JOIN_OVERFLOWS"                     BIGINT
,   "HASH_JOIN_SMALL_OVERFLOWS"               BIGINT
,   "POST_SHRTHRESHOLD_HASH_JOINS"            BIGINT
,   "TOTAL_OLAP_FUNCS"                        BIGINT
,   "OLAP_FUNC_OVERFLOWS"                     BIGINT
,   "INT_ROWS_DELETED"                        BIGINT
,   "INT_ROWS_INSERTED"                       BIGINT
,   "INT_ROWS_UPDATED"                        BIGINT
,   "POOL_COL_L_READS"                        BIGINT
,   "POOL_TEMP_COL_L_READS"                   BIGINT
,   "POOL_COL_P_READS"                        BIGINT
,   "POOL_TEMP_COL_P_READS"                   BIGINT
,   "POOL_COL_LBP_PAGES_FOUND"                BIGINT
,   "POOL_COL_WRITES"                         BIGINT
,   "POOL_COL_GBP_L_READS"                    BIGINT
,   "POOL_COL_GBP_P_READS"                    BIGINT
,   "POOL_COL_GBP_INVALID_PAGES"              BIGINT
,   "POOL_COL_GBP_INDEP_PAGES_FOUND_IN_LBP"   BIGINT
,   "POOL_QUEUED_ASYNC_COL_REQS"              BIGINT
,   "POOL_QUEUED_ASYNC_TEMP_COL_REQS"         BIGINT
,   "POOL_QUEUED_ASYNC_COL_PAGES"             BIGINT
,   "POOL_QUEUED_ASYNC_TEMP_COL_PAGES"        BIGINT
,   "POOL_FAILED_ASYNC_COL_REQS"              BIGINT
,   "POOL_FAILED_ASYNC_TEMP_COL_REQS"         BIGINT
,   "TOTAL_COL_TIME"                          BIGINT
,   "TOTAL_COL_PROC_TIME"                     BIGINT
,   "TOTAL_COL_EXECUTIONS"                    BIGINT
,   "COMM_EXIT_WAIT_TIME"                     BIGINT
,   "COMM_EXIT_WAITS"                         BIGINT
,   "POST_THRESHOLD_HASH_JOINS"               BIGINT
,   "POOL_DATA_CACHING_TIER_L_READS"          BIGINT
,   "POOL_INDEX_CACHING_TIER_L_READS"         BIGINT
,   "POOL_XDA_CACHING_TIER_L_READS"           BIGINT
,   "POOL_COL_CACHING_TIER_L_READS"           BIGINT
,   "POOL_DATA_CACHING_TIER_PAGE_WRITES"      BIGINT
,   "POOL_INDEX_CACHING_TIER_PAGE_WRITES"     BIGINT
,   "POOL_XDA_CACHING_TIER_PAGE_WRITES"       BIGINT
,   "POOL_COL_CACHING_TIER_PAGE_WRITES"       BIGINT
,   "POOL_DATA_CACHING_TIER_PAGE_UPDATES"     BIGINT
,   "POOL_INDEX_CACHING_TIER_PAGE_UPDATES"    BIGINT
,   "POOL_XDA_CACHING_TIER_PAGE_UPDATES"      BIGINT
,   "POOL_COL_CACHING_TIER_PAGE_UPDATES"      BIGINT
,   "POOL_CACHING_TIER_PAGE_READ_TIME"        BIGINT
,   "POOL_CACHING_TIER_PAGE_WRITE_TIME"       BIGINT
,   "POOL_DATA_CACHING_TIER_PAGES_FOUND"      BIGINT
,   "POOL_INDEX_CACHING_TIER_PAGES_FOUND"     BIGINT
,   "POOL_XDA_CACHING_TIER_PAGES_FOUND"       BIGINT
,   "POOL_COL_CACHING_TIER_PAGES_FOUND"       BIGINT
,   "POOL_DATA_CACHING_TIER_GBP_INVALID_PAGES" BIGINT
,   "POOL_INDEX_CACHING_TIER_GBP_INVALID_PAGES" BIGINT
,   "POOL_XDA_CACHING_TIER_GBP_INVALID_PAGES" BIGINT
,   "POOL_COL_CACHING_TIER_GBP_INVALID_PAGES" BIGINT
,   "POOL_DATA_CACHING_TIER_GBP_INDEP_PAGES_FOUND" BIGINT
,   "POOL_INDEX_CACHING_TIER_GBP_INDEP_PAGES_FOUND" BIGINT
,   "POOL_XDA_CACHING_TIER_GBP_INDEP_PAGES_FOUND" BIGINT
,   "POOL_COL_CACHING_TIER_GBP_INDEP_PAGES_FOUND" BIGINT
,   "TOTAL_HASH_GRPBYS"                       BIGINT
,   "HASH_GRPBY_OVERFLOWS"                    BIGINT
,   "POST_THRESHOLD_HASH_GRPBYS"              BIGINT
,   "POST_THRESHOLD_OLAP_FUNCS"               BIGINT
,   "EXT_TABLE_RECV_WAIT_TIME"                BIGINT
,   "EXT_TABLE_RECVS_TOTAL"                   BIGINT
,   "EXT_TABLE_RECV_VOLUME"                   BIGINT
,   "EXT_TABLE_READ_VOLUME"                   BIGINT
,   "EXT_TABLE_SEND_WAIT_TIME"                BIGINT
,   "EXT_TABLE_SENDS_TOTAL"                   BIGINT
,   "EXT_TABLE_SEND_VOLUME"                   BIGINT
,   "EXT_TABLE_WRITE_VOLUME"                  BIGINT
,   "SEMANTIC_ENV_ID"                         BIGINT
,   "STMTID"                                  BIGINT
,   "PLANID"                                  BIGINT
,   "PREP_WARNING"                            INTEGER
,   "PREP_WARNING_REASON"                     INTEGER
,   "POST_THRESHOLD_COL_VECTOR_CONSUMERS"     BIGINT
,   "TOTAL_COL_VECTOR_CONSUMERS"              BIGINT
,   "ACTIVE_HASH_GRPBYS_TOP"                  BIGINT
,   "ACTIVE_HASH_JOINS_TOP"                   BIGINT
,   "ACTIVE_OLAP_FUNCS_TOP"                   BIGINT
,   "ACTIVE_PEAS_TOP"                         BIGINT
,   "ACTIVE_PEDS_TOP"                         BIGINT
,   "ACTIVE_SORT_CONSUMERS_TOP"               BIGINT
,   "ACTIVE_SORTS_TOP"                        BIGINT
,   "ACTIVE_COL_VECTOR_CONSUMERS_TOP"         BIGINT
,   "SORT_CONSUMER_HEAP_TOP"                  BIGINT
,   "SORT_CONSUMER_SHRHEAP_TOP"               BIGINT
,   "SORT_HEAP_TOP"                           BIGINT
,   "SORT_SHRHEAP_TOP"                        BIGINT
,   "TOTAL_INDEX_BUILD_TIME"                  BIGINT
,   "TOTAL_INDEX_BUILD_PROC_TIME"             BIGINT
,   "TOTAL_INDEXES_BUILT"                     BIGINT
,   "FCM_TQ_RECV_WAITS_TOTAL"                 BIGINT
,   "FCM_MESSAGE_RECV_WAITS_TOTAL"            BIGINT
,   "FCM_TQ_SEND_WAITS_TOTAL"                 BIGINT
,   "FCM_MESSAGE_SEND_WAITS_TOTAL"            BIGINT
,   "FCM_SEND_WAITS_TOTAL"                    BIGINT
,   "FCM_RECV_WAITS_TOTAL"                    BIGINT
,   "COL_VECTOR_CONSUMER_OVERFLOWS"           BIGINT
,   "TOTAL_COL_SYNOPSIS_TIME"                 BIGINT
,   "TOTAL_COL_SYNOPSIS_PROC_TIME"            BIGINT
,   "TOTAL_COL_SYNOPSIS_EXECUTIONS"           BIGINT
,   "COL_SYNOPSIS_ROWS_INSERTED"              BIGINT
,   "LOB_PREFETCH_WAIT_TIME"                  BIGINT
,   "LOB_PREFETCH_REQS"                       BIGINT
,   "FED_ROWS_DELETED"                        BIGINT
,   "FED_ROWS_INSERTED"                       BIGINT
,   "FED_ROWS_UPDATED"                        BIGINT
,   "FED_ROWS_READ"                           BIGINT
,   "FED_WAIT_TIME"                           BIGINT
,   "FED_WAITS_TOTAL"                         BIGINT
,   "ADM_OVERFLOWS"                           BIGINT
,   "ADM_BYPASS_ACT_TOTAL"                    BIGINT
,   "ESTIMATED_SORT_SHRHEAP_TOP"              BIGINT
,   "ESTIMATED_SORT_CONSUMERS_TOP"            BIGINT
,   "ESTIMATED_RUNTIME"                       BIGINT
,   "AGENTS_TOP"                              BIGINT
,   "LAST_EXEC_ERROR"                         INTEGER
,   "LAST_EXEC_ERROR_SQLERRMC"                VARCHAR(70 OCTETS)
,   "LAST_EXEC_ERROR_TIMESTAMP"               TIMESTAMP
,   "LAST_EXEC_WARNING"                       INTEGER
,   "LAST_EXEC_WARNING_SQLERRMC"              VARCHAR(70 OCTETS)
,   "LAST_EXEC_WARNING_TIMESTAMP"             TIMESTAMP
,   "NUM_EXEC_WITH_ERROR"                     BIGINT
,   "NUM_EXEC_WITH_WARNING"                   BIGINT
,   "STMT_TEXT"                               CLOB(2097152 OCTETS) INLINE LENGTH 164
,   "COMP_ENV_DESC"                           BLOB(10240) INLINE LENGTH 116
,   "MAX_COORD_STMT_EXEC_TIME_ARGS"           BLOB(10485760) INLINE LENGTH 196
,   "STMT_COMMENTS"                           BLOB(10240) INLINE LENGTH 116
)
--ORGANIZE BY ROW
DISTRIBUTE BY ("EXECUTABLE_ID")
--IN "USERSPACE1"
@