#! /bin/sh
#############################################################################
# (c) Copyright IBM Corp. 2007 All rights reserved. 
# 
# The following sample of source code ("Sample") is owned by International 
# Business Machines Corporation or one of its subsidiaries ("IBM") and is 
# copyrighted and licensed, not sold. You may use, copy, modify, and 
# distribute the Sample in any form without payment to IBM, for the purpose of 
# assisting you in the development of your applications.
# 
# The Sample code is provided to you on an "AS IS" basis, without warranty of 
# any kind. IBM HEREBY EXPRESSLY DISCLAIMS ALL WARRANTIES, EITHER EXPRESS OR 
# IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF 
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. Some jurisdictions do 
# not allow for the exclusion or limitation of implied warranties, so the above 
# limitations or exclusions may not apply to you. IBM shall not be liable for 
# any damages you suffer as a result of using, copying, modifying or 
# distributing the Sample, even if IBM has been advised of the possibility of 
# such damages.
#############################################################################
# SCRIPT: bldmc
# Builds C multi-connection applications for Linux
# Requires a second database: <alias2>. Suggested name: sample2
# Also requires three program source files: <prog_name> and <prog_name1> 
# to be bound to the first database; <prog_name2> to be bound to the 
# second database.

if (($# < 3))
then
  echo "Usage: bldmc <prog_name> <alias1> <alias2> [ <uid1> <pwd1> <uid2> <pwd2> ]"
  exit
fi

# Select the compiler to use 
CC=gcc 
#CC=xlc_r 

# Set DB2PATH to where DB2 will be accessed.
# The default is the standard instance path.
DB2PATH=$HOME/sqllib

# To specify a runtime path for shared libraries, uncomment the
# following line (usually only needed for setuid applications).
# RUNTIME=true

# Default flags
EXTRA_C_FLAGS=""

# Figure out which Linux architecture we are on
HARDWAREPLAT=`uname -m`

# Default to native bitwidth for the platform
if [ "$HARDWAREPLAT" = "x86_64" ] || [ "$HARDWAREPLAT" = "ppc64" ] || 
   [ "$HARDWAREPLAT" = "s390x" ] || [ "$HARDWAREPLAT" = "ia64" ] ||
   [ "$HARDWAREPLAT" = "ppc64le" ]
then
  BITWIDTH=64
else
  # x86 is the only native 32-bit platform
  BITWIDTH=32
fi

# Uncomment the next line to force a 32-bit application compile/link
#BITWIDTH=32

# Set flags for 32-bit compilation on non-native 32-bit platforms
if [ $BITWIDTH = "32" ]
then
  LIB="lib32"
  if [ "$HARDWAREPLAT" = "s390x" ]
  then
    EXTRA_C_FLAGS="-m31"
  else
    if [ "$HARDWAREPLAT" = "ia64" ]
    then
      # DB2 does not support 32-bit applications on Linux on IA64
      BITWIDTH=64
    else
      EXTRA_C_FLAGS="-m32"
    fi
  fi
fi

# Set flags for 64-bit compilation
if [ $BITWIDTH = "64" ]
then
  LIB="lib64"
  if [ "$HARDWAREPLAT" != "ia64" ]
  then
    # gcc on ia64 does not support the -m64 flag
    EXTRA_C_FLAGS="-m64"
  fi
fi

# Setup the embedded library path
EXTRA_LFLAG="-Wl,-rpath,$DB2PATH/$LIB"

# Precompile and bind the program files
./embprep $1  $2 $4 $5
./embprep $11 $2 $4 $5
./embprep $12 $3 $6 $7

# Compile the program files
$CC $EXTRA_C_FLAGS -I$DB2PATH/include -c $1.c $11.c $12.c utilemb.c

# Link the program
$CC $EXTRA_C_FLAGS -o $1 $1.o $11.o $12.o utilemb.o $EXTRA_LFLAG -L$DB2PATH/$LIB -ldb2
