-- Script to migrate Monitor control tables from V8 to V9.1.
--
-- Prior to running this script, customize it to your existing 
-- monitor control server environment:
-- (1) Locate and change all occurrences of the string !REPLMONTS1! 
--     to the name of the tablespace where the ASN.IBMSNAP_CONDITIONS
--     monitor control table currently resides
--

ALTER TABLE ASN.IBMSNAP_CONTACTS VOLATILE CARDINALITY;
ALTER TABLE ASN.IBMSNAP_ALERTS VOLATILE CARDINALITY;
ALTER TABLE ASN.IBMSNAP_MONPARMS VOLATILE CARDINALITY;
ALTER TABLE ASN.IBMSNAP_GROUPS VOLATILE CARDINALITY;
ALTER TABLE ASN.IBMSNAP_CONTACTGRP VOLATILE CARDINALITY;
ALTER TABLE ASN.IBMSNAP_CONDITIONS VOLATILE CARDINALITY;
ALTER TABLE ASN.IBMSNAP_MONSERVERS VOLATILE CARDINALITY;
ALTER TABLE ASN.IBMSNAP_MONTRACE VOLATILE CARDINALITY;


CREATE TABLE ASN.IBMSNAP_TEMPLATES(
TEMPLATE_NAME                   VARCHAR(128) NOT NULL,
START_TIME                      TIME NOT NULL,
WDAY                            SMALLINT,
DURATION                        INT NOT NULL,
PRIMARY KEY(TEMPLATE_NAME))
IN REPLMONTS1;

ALTER TABLE ASN.IBMSNAP_TEMPLATES VOLATILE CARDINALITY;

CREATE TABLE ASN.IBMSNAP_SUSPENDS(
SUSPENSION_NAME                 VARCHAR(128) NOT NULL,
SERVER_NAME                     CHAR(18) NOT NULL,
SERVER_ALIAS                    CHAR(8),
TEMPLATE_NAME                   VARCHAR(128),
START                           TIMESTAMP NOT NULL,
STOP                            TIMESTAMP NOT NULL,
PRIMARY KEY(SUSPENSION_NAME))
IN REPLMONTS1;

CREATE UNIQUE INDEX ASN.IBMSNAP_SUSPENDSX
ON ASN.IBMSNAP_SUSPENDS(
SERVER_NAME                     ASC,
START                           ASC,
TEMPLATE_NAME                   ASC);

ALTER TABLE ASN.IBMSNAP_SUSPENDS VOLATILE CARDINALITY;

ALTER TABLE ASN.IBMSNAP_MONTRAIL
  ADD COLUMN SUSPENSION_NAME VARCHAR(128) WITH DEFAULT NULL;
  
ALTER TABLE ASN.IBMSNAP_MONPARMS
  ALTER COLUMN ARCH_LEVEL SET DEFAULT '0901'
  ALTER COLUMN MONITOR_INTERVAL SET DEFAULT 300000;  

UPDATE ASN.IBMSNAP_MONPARMS SET ARCH_LEVEL = '0901';

UPDATE ASN.IBMSNAP_MONPARMS 
  SET MONITOR_INTERVAL = MONITOR_INTERVAL * 1000;
