--********************************************************************/
--                                                                   */
--          IBM InfoSphere Replication Server                         */
--      Version 10 for Linux, UNIX AND Windows                       */
--                                                                   */
--     Sample Q Replication migration script for UNIX AND NT         */
--     Licensed Materials - Property of IBM                          */
--                                                                   */
--     (C) Copyright IBM Corp. 1993, 2011. All Rights Reserved       */
--                                                                   */
--     US Government Users Restricted Rights - Use, duplication      */
--     or disclosure restricted by GSA ADP Schedule Contract         */
--     with IBM Corp.                                                */
--                                                                   */
--********************************************************************/
-- Q Capture Migration script (asnqcapluwv10.sql)

-- Script to migrate Q Capture control tables from V97fp3 to V10.
--
-- Prior to running this script, customize it to your existing 
-- Q Capture server environment:
--
-- (1) Locate and change all occurrences of the string !CAPSCHEMA! 
--     to the name of the Q Capture schema applicable to your
--     environment.
-- (2) Locate and change all occurrences of the string !CAPTABLESPACE! 
--     to the name of the tablespace where your Q Capture control tables
--     are created.
-- (3) Run the script to migrate control tables into V10.
--
--

UPDATE !CAPSCHEMA!.IBMQREP_CAPPARMS   SET ARCH_LEVEL = '1001';  

ALTER TABLE !CAPSCHEMA!.IBMQREP_CAPPARMS 
  ADD COLUMN WARNTXSZ INTEGER NOT NULL WITH DEFAULT 0;
ALTER TABLE !CAPSCHEMA!.IBMQREP_CAPPARMS 
  ADD COLUMN LOGSPOOLING CHARACTER(1) NOT NULL WITH DEFAULT 'N';  

CREATE TABLE !CAPSCHEMA!.IBMQREP_SCHEMASUBS
(
 SCHEMA_SUBNAME VARCHAR(64) NOT NULL,
 QMAPNAME VARCHAR(128) NOT NULL,
 SCHEMA_NAME VARCHAR(128) NOT NULL,
 OBJECT_NAME  VARCHAR(128) NOT NULL WITH DEFAULT '%',
 SUBPROFNAME VARCHAR(128) NOT NULL WITH DEFAULT 'ASNBIDI',
 SUBGROUP VARCHAR(30),
 SOURCE_NODE SMALLINT NOT NULL WITH DEFAULT 0,
 TARGET_NODE SMALLINT NOT NULL WITH DEFAULT 0,
 STATE CHARACTER(1) NOT NULL WITH DEFAULT 'N',
 STATE_TIME TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
 STATE_INFO CHAR(8),
 PRIMARY KEY(SCHEMA_SUBNAME)
 )  IN !CAPTABLESPACE!;
 
CREATE TABLE !CAPSCHEMA!.IBMQREP_EXCLSCHEMA
(
 SCHEMA_NAME VARCHAR(128) NOT NULL, 
 OBJECT_NAME  VARCHAR(128) NOT NULL WITH DEFAULT '%',
 QMAPNAME VARCHAR(128) NOT NULL
 )  IN !CAPTABLESPACE!;
 
 CREATE TABLE !CAPSCHEMA!.IBMQREP_SUBS_PROF
( SUBPROFNAME      VARCHAR(128) NOT NULL,
 SUBNAME_PREFIX    CHAR(4),
 SUBTYPE           CHAR(1) NOT NULL WITH DEFAULT 'U',
 CHANGED_COLS_ONLY CHAR(1) NOT NULL WITH DEFAULT 'Y',
 HAS_LOADPHASE     CHAR(1) NOT NULL WITH DEFAULT 'I',
 SUPPRESS_DELETES  CHAR(1) NOT NULL WITH DEFAULT 'N',
 CAPTURE_LOAD      CHAR(1) NOT NULL WITH DEFAULT 'W',
 CONFLICT_RULE     CHAR(1) NOT NULL WITH DEFAULT 'K',
 CONFLICT_ACTION   CHAR(1) NOT NULL WITH DEFAULT 'I',
 ERROR_ACTION      CHAR(1) NOT NULL WITH DEFAULT 'Q',
 OKSQLSTATES       VARCHAR(128) WITH DEFAULT NULL,
 LOAD_TYPE         SMALLINT NOT NULL WITH DEFAULT 0,
 MODELQ            VARCHAR(36) NOT NULL WITH DEFAULT 'IBMQREP.SPILL.MODELQ',
 IGNTRIG           CHAR(1) NOT NULL WITH DEFAULT 'N',
 IGNCASDEL         CHAR(1) NOT NULL WITH DEFAULT 'N',
 IGNSETNULL        CHAR(1) NOT NULL WITH DEFAULT 'N',
 CAPTURE_TRUNCATE  CHAR(1) NOT NULL WITH DEFAULT 'R',
 PRIMARY KEY (SUBPROFNAME)
 ) IN !CAPTABLESPACE!;

ALTER TABLE !CAPSCHEMA!.IBMQREP_SUBS 
  ADD COLUMN SCHEMA_SUBNAME VARCHAR(64);
ALTER TABLE !CAPSCHEMA!.IBMQREP_SUBS   
  ADD COLUMN SUB_CREATOR VARCHAR(12) WITH DEFAULT NULL;
ALTER TABLE !CAPSCHEMA!.IBMQREP_SUBS 
  ADD COLUMN IGNSETNULL CHAR(1) NOT NULL WITH DEFAULT 'N';
ALTER TABLE !CAPSCHEMA!.IBMQREP_SUBS   
  ADD COLUMN REPL_ADDCOL CHAR(1) NOT NULL WITH DEFAULT 'N';
ALTER TABLE !CAPSCHEMA!.IBMQREP_SUBS   
  ADD COLUMN CAPTURE_TRUNCATE CHAR(1) NOT NULL WITH DEFAULT 'R';
  

CREATE TABLE !CAPSCHEMA!.IBMQREP_TABVERSION
( LSN             VARCHAR(16) FOR BIT DATA NOT NULL,
 TABLEID1         SMALLINT NOT NULL,
 TABLEID2         SMALLINT NOT NULL,
 VERSION          INTEGER NOT NULL,
 SOURCE_OWNER     VARCHAR(128) NOT NULL,
 SOURCE_NAME      VARCHAR(128) NOT NULL)
  IN !CAPTABLESPACE!;

CREATE UNIQUE INDEX !CAPSCHEMA!.IBMQREP_TABVERSIOX ON
 !CAPSCHEMA!.IBMQREP_TABVERSION
( LSN, TABLEID1, TABLEID2, VERSION);

CREATE INDEX !CAPSCHEMA!.IBMQREP_TABVERSIOX1 ON
 !CAPSCHEMA!.IBMQREP_TABVERSION
( TABLEID1 ASC, TABLEID2 ASC);

CREATE INDEX !CAPSCHEMA!.IBMQREP_TABVERSIOX2 ON
 !CAPSCHEMA!.IBMQREP_TABVERSION
( SOURCE_OWNER ASC, SOURCE_NAME ASC);

CREATE TABLE !CAPSCHEMA!.IBMQREP_COLVERSION
( LSN       VARCHAR(16) FOR BIT DATA,
 TABLEID1   SMALLINT NOT NULL,
 TABLEID2   SMALLINT NOT NULL,
 POSITION   SMALLINT NOT NULL,
 NAME       VARCHAR(128) NOT NULL,
 TYPE       SMALLINT NOT NULL,
 LENGTH     INTEGER NOT NULL,
 NULLS      CHAR(1) NOT NULL,
 DEFAULT    VARCHAR(1536),
 CODEPAGE   INTEGER,
 SCALE      INTEGER)
  IN !CAPTABLESPACE!;

CREATE UNIQUE INDEX !CAPSCHEMA!.IBMQREP_COLVERSIOX ON
 !CAPSCHEMA!.IBMQREP_COLVERSION
( LSN, TABLEID1, TABLEID2, POSITION);


CREATE INDEX !CAPSCHEMA!.IBMQREP_COLVERSIOX1 ON
 !CAPSCHEMA!.IBMQREP_COLVERSION
( TABLEID1 ASC, TABLEID2 ASC);

 
CREATE INDEX !CAPSCHEMA!.IBMQREP_PART_HISTIDX1 ON
 !CAPSCHEMA!.IBMQREP_PART_HIST
( TABSCHEMA, TABNAME, LSN);


