--# Copyright IBM Corp. All Rights Reserved.
--# SPDX-License-Identifier: Apache-2.0

CREATE OR REPLACE VARIABLE DB_DIAG_FROM_TIMESTAMP TIMESTAMP DEFAULT (TIMESTAMP(CURRENT_DATE))@
CREATE OR REPLACE VARIABLE DB_DIAG_TO_TIMESTAMP TIMESTAMP DEFAULT (CAST(NULL AS TIMESTAMP))@
CREATE OR REPLACE VARIABLE DB_DIAG_MEMBER INTEGER DEFAULT -2@
