CONNECT TO $DATABASE

CREATE OR REPLACE FUNCTION EMBEDDING(varchar(4192), varchar(4192)) RETURNS varchar(4500) \
  LANGUAGE PYTHON  PARAMETER STYLE NPSGENERIC  FENCED  NOT THREADSAFE  NO FINAL CALL NO SQL \
  ALLOW PARALLEL  NO DBINFO  DETERMINISTIC NO EXTERNAL ACTION RETURNS NULL ON NULL INPUT \
  external name '$DB2_UDF_DIR/EMBEDDING_UDSF.py'

CREATE OR REPLACE FUNCTION EMBEDDING_BATCH_INTID(integer, varchar(4192), varchar(4192), bigint) returns table (embedding varchar(4500), id bigint) \
  LANGUAGE PYTHON  parameter style NPSGENERIC  FENCED  NOT THREADSAFE  NO FINAL CALL NO SQL \
  DISALLOW PARALLEL NO DBINFO  DETERMINISTIC NO EXTERNAL ACTION RETURNS NULL ON NULL INPUT \
  external name '$DB2_UDF_DIR/EMBEDDING_BATCH_UDTF.py'

CREATE OR REPLACE FUNCTION EMBEDDING_BATCH_CHARID(integer, varchar(4192), varchar(4192), char(32)) returns table (embedding varchar(4500), id char(32)) \
  LANGUAGE PYTHON  parameter style NPSGENERIC  FENCED  NOT THREADSAFE  NO FINAL CALL NO SQL \
  DISALLOW PARALLEL NO DBINFO  DETERMINISTIC NO EXTERNAL ACTION RETURNS NULL ON NULL INPUT \
  external name '$DB2_UDF_DIR/EMBEDDING_BATCH_UDTF.py'

CREATE OR REPLACE PROCEDURE EMBEDDING_UPDATE (IN TABLE_NAME VARCHAR(128), IN PROMPT_COL VARCHAR(128), IN EMBEDDING_COL VARCHAR(128), IN MODEL_NAME VARCHAR(255) \
) \
  LANGUAGE SQL \
  DYNAMIC RESULT SETS 0 \
BEGIN \
  EXECUTE IMMEDIATE \
    'UPDATE ' || TABLE_NAME || ' ' || \
    'SET ' || EMBEDDING_COL || ' = UDF_RESULT.embedding ' || \
    'FROM ' || TABLE_NAME || ' AS INPUT_TABLE ' || \
    'INNER JOIN TABLE(EMBEDDING_BATCH_CHARID( ' || \
                      '(SELECT COUNT(*) FROM ' || TABLE_NAME || '), ' || \
                      '''' || MODEL_NAME || ''', ' || \
                      'INPUT_TABLE.' || PROMPT_COL || ', ' || \
                      'HEX(INPUT_TABLE.rowid))) AS UDF_RESULT ' || \
    'ON HEX(' || TABLE_NAME ||'.rowid) = UDF_RESULT.id ' || \
    'WHERE HEX(' || TABLE_NAME ||'.rowid) = UDF_RESULT.id'; \
END

CREATE OR REPLACE PROCEDURE EMBEDDING_UPDATE (IN TABLE_NAME VARCHAR(128), IN ID_COL VARCHAR(128), IN PROMPT_COL VARCHAR(128), IN EMBEDDING_COL VARCHAR(128), IN MODEL_NAME VARCHAR(255) \
) \
  LANGUAGE SQL \
  DYNAMIC RESULT SETS 0 \
BEGIN \
  EXECUTE IMMEDIATE \
    'UPDATE ' || TABLE_NAME || ' ' || \
    'SET ' || EMBEDDING_COL || ' = UDF_RESULT.embedding ' || \
    'FROM ' || TABLE_NAME || ' AS INPUT_TABLE ' || \
    'INNER JOIN TABLE(EMBEDDING_BATCH_INTID( ' || \
                      '(SELECT COUNT(*) FROM ' || TABLE_NAME || '), ' || \
                      '''' || MODEL_NAME || ''', ' || \
                      'INPUT_TABLE.' || PROMPT_COL || ', ' || \
                      'INPUT_TABLE.' || ID_COL || ')) AS UDF_RESULT ' || \
    'ON ' || TABLE_NAME ||'.' || ID_COL || ' = UDF_RESULT.id ' || \
    'WHERE ' || TABLE_NAME ||'.' || ID_COL || ' = UDF_RESULT.id'; \
END

CREATE OR REPLACE PROCEDURE EMBEDDING_UPDATE (IN SOURCE_TABLE_NAME VARCHAR(128), IN SOURCE_ID_COL VARCHAR(128), IN SOURCE_PROMPT_COL VARCHAR(128), \
                                              IN TARGET_TABLE_NAME VARCHAR(128), IN TARGET_ID_COL VARCHAR(128), IN TARGET_EMBEDDING_COL VARCHAR(128), \
                                              IN MODEL_NAME VARCHAR(255) \
) \
  LANGUAGE SQL \
  DYNAMIC RESULT SETS 0 \
BEGIN \
  EXECUTE IMMEDIATE \
    'UPDATE ' || TARGET_TABLE_NAME || ' ' || \
    'SET ' || TARGET_EMBEDDING_COL || ' = UDF_RESULT.embedding ' || \
    'FROM ' || SOURCE_TABLE_NAME || ' AS INPUT_TABLE ' || \
    'INNER JOIN TABLE(EMBEDDING_BATCH_INTID( ' || \
                      '(SELECT COUNT(*) FROM ' || SOURCE_TABLE_NAME || '), ' || \
                      '''' || MODEL_NAME || ''', ' || \
                      'INPUT_TABLE.' || SOURCE_PROMPT_COL || ', ' || \
                      'INPUT_TABLE.' || SOURCE_ID_COL || ')) AS UDF_RESULT ' || \
    'ON ' || TARGET_TABLE_NAME || '.' || TARGET_ID_COL || ' = UDF_RESULT.id ' || \
    'WHERE ' || TARGET_TABLE_NAME ||'.' || TARGET_ID_COL || ' = UDF_RESULT.id'; \
END

CREATE OR REPLACE PROCEDURE EMBEDDING_INSERT (IN SOURCE_TABLE_NAME VARCHAR(128), IN SOURCE_ID_COL VARCHAR(128), IN SOURCE_PROMPT_COL VARCHAR(128), \
                                              IN TARGET_TABLE_NAME VARCHAR(128), IN TARGET_ID_COL VARCHAR(128), IN TARGET_EMBEDDING_COL VARCHAR(128), \
                                              IN MODEL_NAME VARCHAR(255) \
) \
  LANGUAGE SQL \
  DYNAMIC RESULT SETS 0 \
BEGIN \
  EXECUTE IMMEDIATE \
    'INSERT INTO ' || TARGET_TABLE_NAME || '(' || TARGET_ID_COL || ',' || TARGET_EMBEDDING_COL || ') ' || \
    'SELECT UDF_RESULT.id, UDF_RESULT.embedding FROM ' || SOURCE_TABLE_NAME || ' AS INPUT_TABLE, ' || \
    'TABLE(EMBEDDING_BATCH_INTID((SELECT COUNT(*) FROM ' || SOURCE_TABLE_NAME || '),' || \
                      '''' || MODEL_NAME || ''', ' || \
                      'INPUT_TABLE.' || SOURCE_PROMPT_COL || ', ' || \
                      'INPUT_TABLE.' || SOURCE_ID_COL || ')) AS UDF_RESULT '; \
END

CONNECT RESET
TERMINATE
