#! /bin/sh
#############################################################################
# (c) Copyright IBM Corp. 2007 All rights reserved.
# 
# The following sample of source code ("Sample") is owned by International 
# Business Machines Corporation or one of its subsidiaries ("IBM") and is 
# copyrighted and licensed, not sold. You may use, copy, modify, and 
# distribute the Sample in any form without payment to IBM, for the purpose of 
# assisting you in the development of your applications.
# 
# The Sample code is provided to you on an "AS IS" basis, without warranty of 
# any kind. IBM HEREBY EXPRESSLY DISCLAIMS ALL WARRANTIES, EITHER EXPRESS OR 
# IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF 
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. Some jurisdictions do 
# not allow for the exclusion or limitation of implied warranties, so the above 
# limitations or exclusions may not apply to you. IBM shall not be liable for 
# any damages you suffer as a result of using, copying, modifying or 
# distributing the Sample, even if IBM has been advised of the possibility of 
# such damages.
#
# Builds a Java embedded SQL (SQLJ) application that uses DataSource
#############################################################################
# SCRIPT: bldsqljds
# Builds UNIX Java embedded SQLJ application that uses DataSource
#  Usage: see usage() function, below

# Translate and compile the SQLJ source file
# and bind the package to the database.


usage(){
	print "usage: bldsqljds <prog_name>"
}

case $1 in
	DbConnDataSource)	
		sqlj Util.sqlj
		sqlj $1.sqlj
		db2sqljcustomize -dataSource jdbc/defaultDataSource -longpkgname $1_SJProfile0
		exit 0;
	;;
	DbConMDataSources)
		sqlj Util.sqlj
		sqlj $1.sqlj
		db2sqljcustomize -dataSource jdbc/DB2SimpleDataSource_ds1 $1_SJProfile0
		db2sqljcustomize -dataSource jdbc/DB2SimpleDataSource_ds2 $1_SJProfile0
		exit 0;
	;;
	Batch1Demo | Batch2Demo | Batch3Demo | ScrollIterDemo)
		sqlj Util.sqlj
		sqlj $1.sqlj
		db2sqljcustomize -dataSource jdbc/DB2SimpleDataSource_ds1 $1_SJProfile0
		exit 0;
	;;
	BlobClobDemo)
		sqlj Util.sqlj
		sqlj $1.sqlj
		db2sqljcustomize -dataSource jdbc/DB2SimpleDataSource_ds1 $1_SJProfile0
		exit 0;
	;;
esac

usage
exit 1


