--********************************************************************/
--                                                                   */
--          IBM InfoSphere Replication Server                        */
--      Version 11.4.0 for Linux, UNIX AND Windows                   */
--                                                                   */
--     Sample Q Replication migration script for UNIX AND Windows    */
--     Licensed Materials - Property of IBM                          */
--                                                                   */
--     (C) Copyright IBM Corp. 2019. All Rights Reserved             */
--                                                                   */
--     US Government Users Restricted Rights - Use, duplication      */
--     or disclosure restricted by GSA ADP Schedule Contract         */
--     with IBM Corp.                                                */
--                                                                   */
--********************************************************************/
-- Script to migrate Oracle Q Apply control tables from V11.1 to V11.5 
--  or higher
--
-- Prior to running this script, customize it to your existing 
-- Q Apply server environment:
-- (1) Locate and change all occurrences of the string !APPSCHEMA! 
--     to the name of the Q Capture schema applicable to your
--     environment
-- (2) Run the script to migrate control tables into V11.5


UPDATE !APPSCHEMA!.IBMQREP_APPLYPARMS SET ARCH_LEVEL = '1140';

ALTER TABLE !APPSCHEMA!.IBMQREP_APPLYPARMS ADD POSSIBLE_LEVEL VARCHAR2(10) DEFAULT NULL;
ALTER TABLE !APPSCHEMA!.IBMQREP_APPLYPARMS ADD CURRENT_LEVEL VARCHAR2(10) DEFAULT '1140.101';
ALTER TABLE !APPSCHEMA!.IBMQREP_APPLYPARMS ADD CONTROL_TABLES_LEVEL VARCHAR2(10) DEFAULT '1140.101';
ALTER TABLE !APPSCHEMA!.IBMQREP_APPLYPARMS ADD SKIP_SPILLEDROW_TABLE CHARACTER(1) DEFAULT 'Y' NOT NULL;

ALTER TABLE !APPSCHEMA!.IBMQREP_RECVQUEUES ADD HAS_FILERECV CHARACTER(1) DEFAULT 'N';
ALTER TABLE !APPSCHEMA!.IBMQREP_RECVQUEUES ADD NUM_STREAM_AGENTS NUMBER(10) DEFAULT 0;
ALTER TABLE !APPSCHEMA!.IBMQREP_RECVQUEUES ADD CAPTURE_LEVEL VARCHAR2(10) DEFAULT NULL;

ALTER TABLE !APPSCHEMA!.IBMQREP_TARGETS  ADD HAS_PARTS CHARACTER(1) DEFAULT 'N';
ALTER TABLE !APPSCHEMA!.IBMQREP_TARGETS  ADD SOURCE_IS_COLUMNAR CHARACTER(1) DEFAULT 'N';

ALTER TABLE !APPSCHEMA!.IBMQREP_TRG_COLS  ADD IS_PART_KEY NUMBER(5) DEFAULT 0 NOT NULL;

ALTER TABLE !APPSCHEMA!.IBMQREP_APPLYMON  ADD TRANS_STREAMING NUMBER(10) DEFAULT NULL;
ALTER TABLE !APPSCHEMA!.IBMQREP_APPLYMON  ADD TRANS_STREAM_BEGIN NUMBER(10) DEFAULT NULL;
ALTER TABLE !APPSCHEMA!.IBMQREP_APPLYMON  ADD TRANS_STREAM_COMMIT NUMBER(10) DEFAULT NULL;
ALTER TABLE !APPSCHEMA!.IBMQREP_APPLYMON  ADD TRANS_STREAM_ROLLBACK NUMBER(10) DEFAULT NULL;
ALTER TABLE !APPSCHEMA!.IBMQREP_APPLYMON  ADD STREAM_CHUNKS_APPLIED NUMBER(10) DEFAULT NULL;
ALTER TABLE !APPSCHEMA!.IBMQREP_APPLYMON  ADD STREAM_CHUNKS_PROCESSED NUMBER(10) DEFAULT NULL;
ALTER TABLE !APPSCHEMA!.IBMQREP_APPLYMON  ADD TABLE_DEPENDENCIES NUMBER(10) DEFAULT NULL;


CREATE TABLE !APPSCHEMA!.IBMQREP_FILE_RECEIVERS
(
 QMAPNAME VARCHAR2(128) NOT NULL,
 FILERECV_PATH VARCHAR2(1040) NOT NULL,
 FILERECV_QUEUE VARCHAR2(48) NOT NULL,
 FILERECV_ACK_QUEUE VARCHAR2(48) NOT NULL,
 FILERECV_PRUNE_LIMIT NUMBER(10) DEFAULT 1440 NOT NULL,
 FILERECV_PARALLEL_DEGREE NUMBER(5) DEFAULT 1 NOT NULL,
 FILERECV_DELETE_IMMED CHARACTER(1) DEFAULT 'N' NOT NULL,
 FILERECV_MAX_DISK_SPACE NUMBER(19) DEFAULT 0 NOT NULL,
 PRIMARY KEY(QMAPNAME)
);


CREATE TABLE !APPSCHEMA!.IBMQREP_FILES_RECEIVED
(
 FILE_ID RAW(16) NOT NULL,
 QMAPNAME VARCHAR2(128) NOT NULL,
 SUB_ID NUMBER(10) NOT NULL,
 UOW RAW(12),
 TARGET_FILENAME VARCHAR2(1040) NOT NULL,
 SOURCE_FILENAME VARCHAR2(1040) NOT NULL,
 STATUS CHARACTER(1) NOT NULL,
 RC NUMBER(10),
 RC_TEXT VARCHAR2(128),
 TOTAL_FILE_SIZE NUMBER(19),
 LAST_BYTE_RECEIVED NUMBER(19),
 LAST_MSG_TIME TIMESTAMP,
 LAST_MSG_SIZE NUMBER(19),
 LAST_MSG_ID RAW(24),
 COORD_MSG_ID RAW(24),
 PRIMARY KEY(FILE_ID, QMAPNAME, SUB_ID)
);


CREATE TABLE !APPSCHEMA!.IBMQREP_FILERECV_MON
(
 MONITOR_TIME TIMESTAMP NOT NULL,
 QMAPNAME VARCHAR2(128) NOT NULL,
 BYTES NUMBER(19),
 MESSAGES NUMBER(10) NOT NULL,
 QDEPTH NUMBER(10) NOT NULL,
 FILES_STARTED NUMBER(10) NOT NULL,
 FILES_COMPLETED NUMBER(10) NOT NULL,
 FILES_DELETED NUMBER(10) NOT NULL,
 FILES_FAILED NUMBER(10) NOT NULL,
 FILES_HOLD NUMBER(10) NOT NULL,
 MQGET_TIME NUMBER(10) NOT NULL,
 DISK_USAGE NUMBER(19) NOT NULL,
 DISK_USAGE_HOLD_FILES NUMBER(19) NOT NULL,
 DISK_FULL_WAIT_TIME NUMBER(10) NOT NULL,
 IDLE_TIME NUMBER(10) NOT NULL,
 PRIMARY KEY(MONITOR_TIME, QMAPNAME)
);
