--********************************************************************/
--                                                                   */
--          IBM InfoSphere Replication Server                        */
--      Version 11.4.0 for Linux, UNIX AND Windows                   */
--                                                                   */
--     Sample Q Replication migration script for UNIX AND Windows    */
--     Licensed Materials - Property of IBM                          */
--                                                                   */
--     (C) Copyright IBM Corp. 2019. All Rights Reserved             */
--                                                                   */
--     US Government Users Restricted Rights - Use, duplication      */
--     or disclosure restricted by GSA ADP Schedule Contract         */
--     with IBM Corp.                                                */
--                                                                   */
--********************************************************************/
-- Script to migrate Oracle Q Capture control tables from V11.1 to V11.5
--  or higher.
--
-- Prior to running this script, customize it to your existing 
-- Q Capture server environment:
-- (1) Locate and change all occurrences of the string !CAPSCHEMA! 
--     to the name of the Q Capture schema applicable to your
--     environment
-- (2) Update the compatibility only after all the Q apply instances are migrated to 1140 level


ALTER TABLE !CAPSCHEMA!.IBMQREP_SENDQUEUES ADD HAS_FILESEND CHARACTER(1) DEFAULT 'N';
ALTER TABLE !CAPSCHEMA!.IBMQREP_SENDQUEUES ADD APPLY_LEVEL VARCHAR2(10) DEFAULT NULL;

UPDATE !CAPSCHEMA!.IBMQREP_SENDQUEUES SET APPLY_LEVEL = (SELECT COMPATIBILITY FROM !CAPSCHEMA!.IBMQREP_CAPPARMS);

UPDATE !CAPSCHEMA!.IBMQREP_CAPPARMS SET ARCH_LEVEL = '1140';

--UPDATE !CAPSCHEMA!.IBMQREP_CAPPARMS SET COMPATIBILITY = '1140';

UPDATE  !CAPSCHEMA!.IBMQREP_CAPPARMS SET LOGRDBUFSZ = 512 WHERE LOGRDBUFSZ = 256;
ALTER TABLE !CAPSCHEMA!.IBMQREP_CAPPARMS ADD IN_MEM_FILTER_EVAL CHARACTER(1) DEFAULT 'Y' NOT NULL;
ALTER TABLE !CAPSCHEMA!.IBMQREP_CAPPARMS ADD USE_CAPCMD_TABLE CHARACTER(1) DEFAULT 'N' NOT NULL;
ALTER TABLE !CAPSCHEMA!.IBMQREP_CAPPARMS ADD CAPCMD_INTERVAL NUMBER(10) DEFAULT 3000 NOT NULL;
ALTER TABLE !CAPSCHEMA!.IBMQREP_CAPPARMS ADD MAX_CAPSTARTS_INTLOAD NUMBER(10) DEFAULT 0 NOT NULL;
ALTER TABLE !CAPSCHEMA!.IBMQREP_CAPPARMS ADD MQTHREAD_BUFSZ NUMBER(10) DEFAULT 4096 NOT NULL;
ALTER TABLE !CAPSCHEMA!.IBMQREP_CAPPARMS ADD PARALLEL_MQTHREAD CHARACTER(1) DEFAULT 'N' NOT NULL;
ALTER TABLE !CAPSCHEMA!.IBMQREP_CAPPARMS ADD POSSIBLE_LEVEL VARCHAR2(10) DEFAULT NULL;
ALTER TABLE !CAPSCHEMA!.IBMQREP_CAPPARMS ADD CURRENT_LEVEL VARCHAR2(10) DEFAULT '1140.101';
ALTER TABLE !CAPSCHEMA!.IBMQREP_CAPPARMS ADD CONTROL_TABLES_LEVEL VARCHAR2(10) DEFAULT '1140.101';
ALTER TABLE !CAPSCHEMA!.IBMQREP_CAPPARMS ADD REMOTE_SOURCE_DB_LOC VARCHAR2(128) DEFAULT NULL;
ALTER TABLE !CAPSCHEMA!.IBMQREP_CAPPARMS ADD ON_REMOTE_SOURCE_UNAVAIL CHARACTER(1) DEFAULT NULL;

ALTER TABLE !CAPSCHEMA!.IBMQREP_SRC_COLS ADD IS_PART_KEY NUMBER(5) DEFAULT 0 ;

ALTER TABLE !CAPSCHEMA!.IBMQREP_CAPMON ADD PARALLEL_PUBLISH_WAIT NUMBER(10);
ALTER TABLE !CAPSCHEMA!.IBMQREP_CAPMON ADD NUM_MQCMITS NUMBER(10);
ALTER TABLE !CAPSCHEMA!.IBMQREP_CAPMON ADD NUM_LOGREAD_NO_PROG NUMBER(10);
ALTER TABLE !CAPSCHEMA!.IBMQREP_CAPMON ADD NUM_LOGREAD_ERRORS NUMBER(10);
ALTER TABLE !CAPSCHEMA!.IBMQREP_CAPMON ADD NUM_STMTFILES NUMBER(10);

ALTER TABLE !CAPSCHEMA!.IBMQREP_CAPQMON ADD TRANS_STREAMING NUMBER(10);
ALTER TABLE !CAPSCHEMA!.IBMQREP_CAPQMON ADD TRANS_STREAM_BEGIN NUMBER(10);
ALTER TABLE !CAPSCHEMA!.IBMQREP_CAPQMON ADD TRANS_STREAM_COMMIT NUMBER(10);
ALTER TABLE !CAPSCHEMA!.IBMQREP_CAPQMON ADD TRANS_STREAM_ROLLBACK NUMBER(10);
ALTER TABLE !CAPSCHEMA!.IBMQREP_CAPQMON ADD STREAM_CHUNKS_PUBLISHED NUMBER(10);


CREATE TABLE !CAPSCHEMA!.IBMQREP_CAPCMD
(
 CMD_ID NUMBER(19) NOT NULL ,
 CMD_ORIGINATOR VARCHAR2(128) DEFAULT USER NOT NULL ,
 CMD_TEXT VARCHAR2(1024) NOT NULL ,
 CMD_STATE CHARACTER(1) DEFAULT 'P' NOT NULL ,
 CMD_RESULT_MSG VARCHAR2(1024) DEFAULT NULL,
 CMD_STATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL ,
 CMD_RESULT_RC NUMBER(10) DEFAULT NULL
);

CREATE INDEX !CAPSCHEMA!.IX1CAPCMD ON !CAPSCHEMA!.IBMQREP_CAPCMD
(
 CMD_ID
);

CREATE SEQUENCE !CAPSCHEMA!.CAPCMD_SEQ START WITH 1 INCREMENT BY 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER !CAPSCHEMA!.CAPCMD_BEFORE_INSERT
BEFORE INSERT
   ON !CAPSCHEMA!.IBMQREP_CAPCMD
   FOR EACH ROW

DECLARE
   v_seq number(19);

BEGIN

  --Generate the CMD_ID value from APPLYCMD_SEQ
   SELECT !CAPSCHEMA!.CAPCMD_SEQ.NEXTVAL INTO v_seq
   FROM dual;


     --Update the sequence value before INSERT
   :new.CMD_ID := v_seq;

END;
/


CREATE TABLE !CAPSCHEMA!.IBMQREP_CAPCMDOUT
(
 CMD_ID NUMBER(19) NOT NULL,
 CMD_SEQUENCE NUMBER(5) NOT NULL,
 CMD_OUTPUT VARCHAR2(4000) NOT NULL
);


CREATE INDEX !CAPSCHEMA!.IX1CAPCMDOUT ON !CAPSCHEMA!.IBMQREP_CAPCMDOUT
(
 CMD_ID,
 CMD_SEQUENCE
);


CREATE TABLE !CAPSCHEMA!.IBMQREP_FILE_SENDERS
(
 QMAPNAME VARCHAR2(128) NOT NULL,
 FILESEND_PATH VARCHAR2(1040),
 FILESEND_QUEUE VARCHAR2(48) NOT NULL,
 FILESEND_ACK_QUEUE VARCHAR2(48) NOT NULL,
 FILESEND_PARALLEL_DEGREE NUMBER(5) DEFAULT 1 NOT NULL,
 FILESEND_PRUNE_LIMIT NUMBER(10) DEFAULT 1440 NOT NULL,
 PRIMARY KEY(QMAPNAME)
);


CREATE TABLE !CAPSCHEMA!.IBMQREP_FILES_SENT
(
 FILE_ID RAW(16) NOT NULL,
 QMAPNAME VARCHAR2(128) NOT NULL,
 SUB_ID NUMBER(10) NOT NULL,
 UOW RAW(12),
 FILENAME VARCHAR2(1040) NOT NULL,
 STATUS CHARACTER(1) NOT NULL,
 RC NUMBER(10),
 RC_TEXT VARCHAR2(128),
 TOTAL_FILE_SIZE NUMBER(19),
 LAST_BYTE_SENT NUMBER(19),
 FIRST_MSG_TIME TIMESTAMP NOT NULL,
 LAST_MSG_TIME TIMESTAMP,
 LAST_MSG_SIZE NUMBER(19),
 LAST_MSG_ID RAW(24),
 COORD_MSG_ID RAW(24),
 PRIMARY KEY(FILE_ID, QMAPNAME, SUB_ID)
);


CREATE TABLE !CAPSCHEMA!.IBMQREP_FILESEND_MON
(
 MONITOR_TIME TIMESTAMP NOT NULL,
 QMAPNAME VARCHAR2(128) NOT NULL,
 BYTES NUMBER(19),
 MESSAGES NUMBER(10) NOT NULL,
 XMITQDEPTH NUMBER(10) NOT NULL,
 FILES_STARTED NUMBER(10) NOT NULL,
 FILES_COMPLETED NUMBER(10) NOT NULL,
 FILES_DELETED NUMBER(10) NOT NULL,
 FILES_FAILED NUMBER(10) NOT NULL,
 FILES_ACKS NUMBER(10) NOT NULL,
 MQPUT_TIME NUMBER(10) NOT NULL,
 PRIMARY KEY(MONITOR_TIME, QMAPNAME)
);
