#! /bin/sh
#############################################################################
# (c) Copyright IBM Corp. 2007 All rights reserved.
# 
# The following sample of source code ("Sample") is owned by International 
# Business Machines Corporation or one of its subsidiaries ("IBM") and is 
# copyrighted and licensed, not sold. You may use, copy, modify, and 
# distribute the Sample in any form without payment to IBM, for the purpose of 
# assisting you in the development of your applications.
# 
# The Sample code is provided to you on an "AS IS" basis, without warranty of 
# any kind. IBM HEREBY EXPRESSLY DISCLAIMS ALL WARRANTIES, EITHER EXPRESS OR 
# IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF 
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. Some jurisdictions do 
# not allow for the exclusion or limitation of implied warranties, so the above 
# limitations or exclusions may not apply to you. IBM shall not be liable for 
# any damages you suffer as a result of using, copying, modifying or 
# distributing the Sample, even if IBM has been advised of the possibility of 
# such damages.
#############################################################################
# SCRIPT: bldapp
# Builds Micro Focus COBOL applications for Linux
# Usage: bldapp <prog_name> [ <db_name> [ <userid> <password> ]]

# Set DB2PATH to where DB2 will be accessed.
# The default is the standard instance path.
DB2PATH=$HOME/sqllib

# Set COBCPY to include the DB2 COPY files directory.
COBCPY=$COBCPY:$DB2PATH/include/cobol_mf
export COBCPY

# Figure out which Linux architecture we are on
HARDWAREPLAT=`uname -m`

# Default to native bitwidth for the platform
if [ "$HARDWAREPLAT" = "ia64" ] || [ "$HARDWAREPLAT" = "ppc64" ] ||
   [ "$HARDWAREPLAT" = "ppc64le" ] 
then
  # DB2 does not support COBOL applications on these platforms
  echo "DB2 does not support COBOL applications on these platforms"
else
  if [ "$HARDWAREPLAT" = "x86_64" ] || [ "$HARDWAREPLAT" = "s390x" ]
  then
    BITWIDTH=64
  else
    BITWIDTH=32
  fi
fi

# Uncomment the next two lines to force a 32-bit application compile/link
#BITWIDTH=32
#export COBMODE=32

# Set flags for 32-bit compilation on non-native 32-bit platforms
if [ $BITWIDTH = "64" ]
then
  EXTRA_COBOL_FLAG="-C MFSYNC"
  LIB="lib64"
else
  LIB="lib32"
fi

# If an embedded SQL program, precompile and bind it.
if [ -f $1".sqb" ]
then
  ./embprep $1 $2 $3 $4
fi

# Compile the checkerr.cbl error checking utility.
cob $EXTRA_COBOL_FLAG -c -x checkerr.cbl

# Compile the program.
cob $EXTRA_COBOL_FLAG -c -x $1.cbl

# Link the program.
cob -x -o $1 $1.o checkerr.o -L$DB2PATH/$LIB -ldb2 -ldb2gmf
