#! /bin/sh
#############################################################################
# (c) Copyright IBM Corp. 2007 All rights reserved.
# 
# The following sample of source code ("Sample") is owned by International 
# Business Machines Corporation or one of its subsidiaries ("IBM") and is 
# copyrighted and licensed, not sold. You may use, copy, modify, and 
# distribute the Sample in any form without payment to IBM, for the purpose of 
# assisting you in the development of your applications.
# 
# The Sample code is provided to you on an "AS IS" basis, without warranty of 
# any kind. IBM HEREBY EXPRESSLY DISCLAIMS ALL WARRANTIES, EITHER EXPRESS OR 
# IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF 
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. Some jurisdictions do 
# not allow for the exclusion or limitation of implied warranties, so the above 
# limitations or exclusions may not apply to you. IBM shall not be liable for 
# any damages you suffer as a result of using, copying, modifying or 
# distributing the Sample, even if IBM has been advised of the possibility of 
# such damages.
#############################################################################
# SCRIPT: bldrtn
# Builds Micro Focus COBOL routines (stored procedures) for Linux
# Usage: bldrtn <program_name> [ <db_name> ]

# Set DB2PATH to where DB2 will be accessed.
# The default is the standard instance path.
DB2PATH=$HOME/sqllib

# Figure out which Linux architecture we are on
HARDWAREPLAT=`uname -m`

# Default to native bitwidth for the platform
if [ "$HARDWAREPLAT" = "ia64" ] || [ "$HARDWAREPLAT" = "ppc64" ] ||
   [ "$HARDWAREPLAT" = "ppc64le" ] 
then
  # DB2 does not support COBOL apps on these platforms
  echo "DB2 does not support COBOL apps on these platforms"
else
  if [ "$HARDWAREPLAT" = "x86_64" ] || [ "$HARDWAREPLAT" = "s390x" ]  
  then
    BITWIDTH=64
  else
    BITWIDTH=32
  fi
fi

# Uncomment the next two lines to force a 32-bit application compile/link
#BITWIDTH=32
#export COBMODE=32

# Set flags for 32-bit compilation on non-native 32-bit platforms
if [ $BITWIDTH = "64" ]
then
  EXTRA_COBOL_FLAG="-C MFSYNC"
  LIB="lib64"
else
  LIB="lib32"
fi

# Set COBCPY to include the DB2 COPY files directory.
COBCPY=$COBCPY:$DB2PATH/include/cobol_mf
export COBCPY

# Precompile and bind the program.
./embprep $1 $2

# Compile and link the program
cob $EXTRA_COBOL_FLAG -y -o $1 $1.cbl -L$DB2PATH/$LIB -ldb2 -ldb2gmf

# Copy the shared library to the sqllib/function subdirectory.
# Note: the user must have write permission to this directory.
rm -f $DB2PATH/function/$1
cp $1 $DB2PATH/function
