--# Copyright IBM Corp. All Rights Reserved.
--# SPDX-License-Identifier: Apache-2.0

/*
 * Shows current SQL activity (at a member level)
 */

/*
There are more columns in the underlying table function that I have selected.  
*/
CREATE OR REPLACE VIEW DB_ACTIVITY AS
SELECT
    LOCAL_START_TIME::TIMESTAMP(0) START_TIME
,   LAST_REFERENCE_TIME    
,   MEMBER
,   APPLICATION_HANDLE
,   ROWS_READ
,   ROWS_INSERTED
--,   ROWS_MODIFIED
,   ROWS_UPDATED
,   ROWS_DELETED
,   T.STMT_TEXT
,   EFFECTIVE_ISOLATION
,   EFFECTIVE_QUERY_DEGREE
,   CLIENT_USERID
,   CLIENT_WRKSTNNAME
,   ACTIVITY_ID
,   ACTIVITY_TYPE
,   ACTIVITY_STATE
,   APPL_ID
,   CLIENT_ACCTNG
,   CLIENT_APPLNAME
,   NUM_AGENTS
,   AGENTS_TOP
,   COORD_STMT_EXEC_TIME
,   STMT_EXEC_TIME
,   TOTAL_SECTION_TIME
,   TOTAL_SECTION_PROC_TIME
,   TOTAL_EXTENDED_LATCH_WAIT_TIME
,   TOTAL_EXTENDED_LATCH_WAITS
,   TOTAL_COL_TIME
,   TOTAL_COL_PROC_TIME
,   TOTAL_COL_EXECUTIONS
,   EXT_TABLE_RECV_WAIT_TIME
,   EXT_TABLE_RECVS_TOTAL
,   EXT_TABLE_RECV_VOLUME
,   EXT_TABLE_SENDS_TOTAL
,   EXT_TABLE_SEND_VOLUME
,   TOTAL_COL_VECTOR_CONSUMERS
,   ACTIVE_SORT_CONSUMERS_TOP
,   SORT_SHRHEAP_TOP
,   FCM_TQ_RECV_WAITS_TOTAL
,   FCM_MESSAGE_RECV_WAITS_TOTAL
,   FCM_RECV_WAITS_TOTAL
,   ESTIMATED_SORT_SHRHEAP_TOP
,   ESTIMATED_RUNTIME
FROM
    TABLE(MON_GET_ACTIVITY(NULL, -2)) AS T
