--# Copyright IBM Corp. All Rights Reserved.
--# SPDX-License-Identifier: Apache-2.0

/*
 * Shows how many rows per second are being returned, read, inserted etc for active applications
 */

CREATE OR REPLACE VIEW DB_APP_ROWS_PER_SEC AS
SELECT
    APPLICATION_HANDLE      AS HANDLE
,   MIN(LOCAL_START_TIME)   AS LOCAL_START_TIME
,   SECONDS_BETWEEN(CURRENT_TIMESTAMP, MIN(LOCAL_START_TIME)) AS DURATION_SEC
--,   MINUTES_BETWEEN(CURRENT_TIMESTAMP, MIN(LOCAL_START_TIME)) AS DURATION_MIN
,   SUM(ROWS_RETURNED ) AS ROWS_RETURNED
,   SUM(ROWS_RETURNED ) / MAX(1,SECONDS_BETWEEN(CURRENT_TIMESTAMP, MIN(LOCAL_START_TIME))) AS RETURNED_PER_SEC
,   SUM(ROWS_READ    ) AS ROWS_READ
,   SUM(ROWS_READ    ) / MAX(1,SECONDS_BETWEEN(CURRENT_TIMESTAMP, MIN(LOCAL_START_TIME))) AS READ_PER_SEC
,   SUM(ROWS_INSERTED) AS ROWS_INSERTED
,   SUM(ROWS_INSERTED) / MAX(1,SECONDS_BETWEEN(CURRENT_TIMESTAMP, MIN(LOCAL_START_TIME))) AS INSERTED_PER_SEC
,   SUM(ROWS_MODIFIED) AS ROWS_MODIFIED
,   SUM(ROWS_MODIFIED) / MAX(1,SECONDS_BETWEEN(CURRENT_TIMESTAMP, MIN(LOCAL_START_TIME))) AS MODIFIED_PER_SEC
,   SUM(ROWS_UPDATED ) AS ROWS_UPDATED
,   SUM(ROWS_UPDATED ) / MAX(1,SECONDS_BETWEEN(CURRENT_TIMESTAMP, MIN(LOCAL_START_TIME))) AS UPDATES_PER_SEC
,   SUM(ROWS_DELETED ) AS ROWS_DELETED
,   SUM(ROWS_DELETED ) / MAX(1,SECONDS_BETWEEN(CURRENT_TIMESTAMP, MIN(LOCAL_START_TIME))) AS DELETED_PER_SEC
,   MAX(VARCHAR(T.STMT_TEXT,32000)) STMT_TEXT
,   MAX(COORD_STMT_EXEC_TIME)   AS COORD_STMT_EXEC_TIME
,   MAX(STMT_EXEC_TIME)         AS STMT_EXEC_TIME
FROM
    TABLE(MON_GET_ACTIVITY(NULL, -2)) AS T
WHERE
    STMT_TEXT NOT LIKE '%DB_APPL_ROWS_PER_SEC%'
GROUP BY
   APPLICATION_HANDLE
