--# Copyright IBM Corp. All Rights Reserved.
--# SPDX-License-Identifier: Apache-2.0

/*
 * Shows the Original and Optimized SQL for each statement in the explain tables
 */

CREATE OR REPLACE VIEW DB_EXPLAIN_STMT AS
SELECT
    ROW_NUMBER() OVER(ORDER BY EXPLAIN_TIME DESC) AS SEQ
,   O.TOTAL_COST        AS COST
,   O.QUERY_DEGREE      AS DEGREE
,   O.STATEMENT_TEXT    AS STMT  
,   DB_FORMAT_SQL(O.STATEMENT_TEXT)   AS STMT_FORMATED
,   P.STATEMENT_TEXT                  AS OPTIMIZED_STMT
,   DB_FORMAT_SQL(P.STATEMENT_TEXT)   AS OPTIMIZED_STMT_FORMATED
--,   PREDICATES
,   EXPLAIN_TIME
,   STMTNO
,   SECTNO
FROM SYSTOOLS.EXPLAIN_STATEMENT O
LEFT JOIN
    SYSTOOLS.EXPLAIN_STATEMENT  P
USING 
    ( EXPLAIN_TIME, STMTNO, SECTNO )
--LEFT JOIN
--(
--    SELECT
--        EXPLAIN_TIME
--    ,   STMTNO
--    ,   SECTNO
--    ,   LISTAGG(PREDICATE_ID || '/' || OPERATOR_ID || ' ' || CHAR(HOW_APPLIED,5) || ' : ' || TO_CHAR(DECIMAL(FILTER_FACTOR,7,6),'0.9999') || ' : ' || PREDICATE_TEXT, CHR(10)) 
--            WITHIN GROUP (ORDER BY PREDICATE_ID, OPERATOR_ID )  AS PREDICATES
--    FROM
--        SYSTOOLS.EXPLAIN_PREDICATE 
--    GROUP BY
--        EXPLAIN_TIME, STMTNO, SECTNO
--)
--USING
--    ( EXPLAIN_TIME, STMTNO, SECTNO )
WHERE 
    O.EXPLAIN_LEVEL = 'O'
AND P.EXPLAIN_LEVEL IN ('P','S')
