--# Copyright IBM Corp. All Rights Reserved.
--# SPDX-License-Identifier: Apache-2.0

/*
 * Metrics about any external table statements in progress
 */

CREATE OR REPLACE VIEW DB_EXTERNAL_TABLE_PROGRESS AS
SELECT
    LOCAL_START_TIME::TIMESTAMP(0)      AS START_DATETIME
,   ROWS_INSERTED
,   ROWS_MODIFIED
,   EXT_TABLE_RECV_WAIT_TIME/1000   AS RECV_WAIT_SECS
,   EXT_TABLE_SEND_WAIT_TIME/1000   AS SEND_WAIT_SECS
--,   EXT_TABLE_RECVS_TOTAL           AS RECVS_TOTAL
,   DEC(ROUND(EXT_TABLE_RECV_VOLUME /POWER(1024.0,3),2),7,2)     AS RECV_GB   
,   DEC(ROUND(EXT_TABLE_SEND_VOLUME /POWER(1024.0,3),2),7,2)     AS SEND_GB 
,   DEC(ROUND(EXT_TABLE_READ_VOLUME /POWER(1024.0,3),2),7,2)     AS READ_GB   
,   DEC(ROUND(EXT_TABLE_WRITE_VOLUME/POWER(1024.0,3),2),7,2)     AS WRITE_GB
--,   EXT_TABLE_SENDS_TOTAL           AS SENDS_TOTAL   
,   STMT_TEXT
,   MEMBER
,   APPLICATION_HANDLE
FROM
     TABLE(MON_GET_ACTIVITY(NULL, -2)) AS T
WHERE
    EXT_TABLE_RECVS_TOTAL > 0 
OR  EXT_TABLE_SENDS_TOTAL > 0