--# Copyright IBM Corp. All Rights Reserved.
--# SPDX-License-Identifier: Apache-2.0

/*
 * Generates DDL for all Foreign Keys in the database
 */

CREATE OR REPLACE VIEW DB_FOREIGN_KEY_DDL AS
WITH COLS AS (
    SELECT
        TABSCHEMA
    ,   TABNAME
    ,   CONSTNAME
    ,   LISTAGG('"' || COLNAME || '"',', ') WITHIN GROUP (ORDER BY COLSEQ) AS COL_LIST
    FROM
        SYSCAT.KEYCOLUSE
    GROUP BY
        TABSCHEMA
    ,   TABNAME
    ,   CONSTNAME
)
SELECT
    TABSCHEMA
,   TABNAME
,   REFTABSCHEMA    AS PARENT_SCHEMA
,   REFTABNAME      AS PARENT_TABNAME
,   'ALTER TABLE "' || TABSCHEMA || '"."' || TABNAME || '" ADD' 
    || CASE WHEN CONSTNAME NOT LIKE 'SQL%' THEN ' CONSTRAINT "' || CONSTNAME || '"' ELSE '' END
    || ' FOREIGN KEY (' || COL_LIST || ') REFERENCES "' || REFTABSCHEMA || '"."' || REFTABNAME || '"'
    || CASE WHEN PARENT_COLS = COL_LIST THEN '' ELSE '(' || PARENT_COLS || ')' END
    || CASE ENFORCED WHEN 'Y' THEN ' ENFORCED' WHEN 'N' THEN ' NOT ENFORCED' END
    || CASE ENABLEQUERYOPT WHEN 'N' THEN ' DISABLE QUERY OPTIMIZATION' ELSE '' END
    || CASE DELETERULE WHEN 'A' THEN '' ELSE ' ON DELETE ' || CASE DELETERULE WHEN 'C' THEN 'CASCADE' WHEN 'N' THEN 'SET NULL' WHEN 'R' THEN 'RESTRICT' END END
    || CASE UPDATERULE WHEN 'A' THEN '' ELSE ' ON UPDATE RESTRICT ' END 
        AS DDL
,   CONSTNAME
,   REFKEYNAME
FROM
    SYSCAT.TABCONST C
JOIN
    SYSCAT.REFERENCES
USING
    ( TABSCHEMA , TABNAME, CONSTNAME )
JOIN
    COLS
USING
    ( TABSCHEMA , TABNAME, CONSTNAME ) 
JOIN
(
    SELECT TABSCHEMA AS REFTABSCHEMA, TABNAME AS REFTABNAME, CONSTNAME AS REFKEYNAME, COL_LIST AS PARENT_COLS 
    FROM COLS
)
USING
    ( REFTABSCHEMA, REFTABNAME, REFKEYNAME )
JOIN (
    SELECT 
        TABSCHEMA, TABNAME, CONSTNAME
    ,   VARCHAR(LISTAGG('C."' || COLNAME || '" = P."' || REFCOLNAME || '"', ' AND ') WITHIN GROUP (ORDER BY COLSEQ),4000) AS JOIN_CLAUSE
    FROM
          SYSCAT.REFERENCES R
    JOIN  SYSCAT.KEYCOLUSE  C USING (    TABSCHEMA,    TABNAME, CONSTNAME ) 
    JOIN  (SELECT CONSTNAME REFKEYNAME, TABSCHEMA AS REFTABSCHEMA, TABNAME AS REFTABNAME, COLNAME AS REFCOLNAME, COLSEQ FROM SYSCAT.KEYCOLUSE)
                            P USING ( REFTABSCHEMA, REFTABNAME, REFKEYNAME, COLSEQ )
    GROUP BY
        TABSCHEMA, TABNAME, CONSTNAME
    )              
    USING ( CONSTNAME, TABSCHEMA, TABNAME )