--# Copyright IBM Corp. All Rights Reserved.
--# SPDX-License-Identifier: Apache-2.0

/*
 * Shows the size of each data slice . Use to check for overall system data Skew
 */

CREATE OR REPLACE VIEW DB_MEMBER_QUICK_SIZE AS
SELECT 
    T.MEMBER
,   DECIMAL(ROUND(T.TBSP_USED_KB     / (1024 * 1024.0),3),17,3) AS USED_GB
,   DECIMAL(ROUND(T.TBSP_PAGE_TOP_KB / (1024 * 1024.0),3),17,3) AS PAGE_TOP_GB
,   DECIMAL(ROUND(T.TBSP_TOTAL_KB    / (1024 * 1024.0),3),17,3) AS TBSP_TOTAL_GB
FROM
(    SELECT
        T.MEMBER
	,   SUM(T.TBSP_PAGE_TOP    * T.TBSP_PAGE_SIZE / BIGINT(1024))  AS TBSP_PAGE_TOP_KB
	,   SUM(T.TBSP_TOTAL_PAGES * T.TBSP_PAGE_SIZE / BIGINT(1024))  AS TBSP_TOTAL_KB
	,   SUM(T.TBSP_USED_PAGES  * T.TBSP_PAGE_SIZE / BIGINT(1024))  AS TBSP_USED_KB
	FROM
        TABLE(MON_GET_TABLESPACE(NULL,-2)) T
	GROUP BY 
	    T.MEMBER
) T