--# Copyright IBM Corp. All Rights Reserved.
--# SPDX-License-Identifier: Apache-2.0

/*
 * Generates DDL for all Primary Keys and Unique Constraints in the database
 */

CREATE OR REPLACE VIEW DB_PRIMARY_KEY_DDL AS
SELECT
    TABSCHEMA
,   TABNAME
,   CONSTNAME
,   'ALTER TABLE "' || RTRIM(TABSCHEMA) || '"."' || TABNAME || '" ADD' 
    || CASE WHEN CONSTNAME NOT LIKE 'SQL%' THEN ' CONSTRAINT "' || CONSTNAME || '"' ELSE '' END
    || CASE C.TYPE WHEN 'P' THEN ' PRIMARY KEY ' WHEN 'U' THEN ' UNIQUE ' END
    || '(' || COL_LIST  
    || COALESCE(', ' || PERIODNAME || CASE PERIODPOLICY WHEN 'O' THEN ' WITHOUT OVERLAPS ' ELSE '' END,'')
    || ')'
    || CASE ENFORCED WHEN 'Y' THEN ' ENFORCED' WHEN 'N' THEN ' NOT ENFORCED' END
    || CASE ENABLEQUERYOPT WHEN 'N' THEN ' DISABLE QUERY OPTIMIZATION' ELSE '' END
        AS DDL
FROM
    SYSCAT.TABCONST C
JOIN
(   SELECT
        K.TABSCHEMA
    ,   K.TABNAME
    ,   K.CONSTNAME
    ,   LISTAGG('"' || K.COLNAME || '"',', ') WITHIN GROUP (ORDER BY K.COLSEQ)   AS COL_LIST
    FROM
        SYSCAT.KEYCOLUSE K
    LEFT JOIN -- exclude period columns from the column list
        SYSCAT.PERIODS  B1 ON K.TABSCHEMA = B1.TABSCHEMA AND K.TABNAME = B1.TABNAME AND K.COLNAME = B1.BEGINCOLNAME AND B1.PERIODNAME = 'BUSINESS_TIME'
    LEFT JOIN
        SYSCAT.PERIODS  B2 ON K.TABSCHEMA = B2.TABSCHEMA AND K.TABNAME = B2.TABNAME AND K.COLNAME = B2.ENDCOLNAME   AND B2.PERIODNAME = 'BUSINESS_TIME'
    WHERE
        B1.TABNAME IS NULL
    AND B2.TABNAME IS NULL
    GROUP BY
        K.TABSCHEMA
    ,   K.TABNAME
    ,   K.CONSTNAME
)
USING
    ( TABSCHEMA , TABNAME, CONSTNAME ) 
WHERE  
    C.TYPE IN ( 'P', 'U' )
