--# Copyright IBM Corp. All Rights Reserved.
--# SPDX-License-Identifier: Apache-2.0

/*
 * WLM Service Classes 
 */

CREATE OR REPLACE VIEW DB_SERVICE_CLASSES AS
SELECT
    COALESCE(S.PARENTSERVICECLASSNAME || '.' ,'') || S.SERVICECLASSNAME      AS SERVICE_CLASS  
,   CPUSHARES      || CASE CPUSHARETYPE      WHEN 'H' THEN ' HARD' WHEN 'S' THEN ' SOFT' ELSE '' END AS CPU_SHARE
,   RESOURCESHARES || CASE RESOURCESHARETYPE WHEN 'H' THEN ' HARD' WHEN 'S' THEN ' SOFT' ELSE '' END AS RESOURCE_SHARE
,   CASE WHEN AGENTPRIORITY = -32768 THEN 0 ELSE AGENTPRIORITY END    AS AGENT_PRI
,   PREFETCHPRIORITY    AS PREF_PRI
,   BUFFERPOOLPRIORITY  AS BUFF_PRI
FROM
    SYSCAT.SERVICECLASSES S
WHERE
    SERVICECLASSNAME       NOT LIKE 'SYS%'
