--# Copyright IBM Corp. All Rights Reserved.
--# SPDX-License-Identifier: Apache-2.0

/*
 * WLM Workload DDL 
 */

CREATE OR REPLACE VIEW DB_SERVICE_CLASS_DDL AS
SELECT
    SERVICECLASSNAME
,   PARENTSERVICECLASSNAME
--,   COALESCE(S.PARENTSERVICECLASSNAME || '.' ,'') || S.SERVICECLASSNAME      AS SERVICE_CLASS  
,   'CREATE SERVICE CLASS ' || SERVICECLASSNAME
    ||  CASE WHEN PARENTSERVICECLASSNAME IS NOT NULL THEN CHR(10) || '    UNDER ' || PARENTSERVICECLASSNAME ELSE '' END
    ||  CASE WHEN WORKLOADTYPE > 1 
            THEN CHR(10) || '    FOR WORKLOAD TYPE ' || CASE WORKLOADTYPE WHEN 1 THEN 'CUSTOM' WHEN 2 THEN 'MIXED' WHEN 3 THEN 'INTERACTIVE' WHEN 4 THEN 'BATCH' END ELSE '' END
    ||  CASE WHEN NOT RESOURCESHARES = 1000 AND RESOURCESHARETYPE = 'S' THEN 
            CHR(10) || '    ' || CASE RESOURCESHARETYPE WHEN 'S' THEN 'SOFT' WHEN 'H' THEN 'HARD' ELSE '' END || ' RESOURCE SHARES ' || RESOURCESHARES ELSE '' END
    ||  CASE WHEN NOT      CPUSHARES = 1000 AND      CPUSHARETYPE = 'H' THEN 
            CHR(10) || '    ' || CASE CPUSHARETYPE WHEN 'S' THEN 'SOFT' WHEN 'H' THEN 'HARD' ELSE '' END || ' CPU SHARES ' || RESOURCESHARES ELSE '' END
    ||  CASE WHEN NOT      CPULIMIT = -1 THEN 
                      ' CPULIMIT ' || CPULIMIT ELSE '' END
    ||  CASE WHEN MINRESOURCESHAREPCT > 0 THEN CHR(10) || '    MINIMUM RESOURCE SHARE ' || MINRESOURCESHAREPCT || ' PERCENT' ELSE '' END
    ||  CASE WHEN ADMISSIONQUEUEORDER NOT IN ('','F') THEN CHR(10) || '    ADMISSION QUEUE ORDER LATENCY' ELSE '' END
    ||  CASE WHEN NOT (DEGREESCALEBACK = 'D' AND PARENTSERVICECLASSNAME IS NOT NULL)
              AND NOT (DEGREESCALEBACK = 'Y' AND PARENTSERVICECLASSNAME IS NULL) 
               THEN CHR(10) || '    DEGREE SCALEBACK ' || CASE DEGREESCALEBACK WHEN 'Y' THEN 'ON' WHEN 'N' THEN 'NO' WHEN 'D' THEN 'DEFAULT' END
           ELSE '' END
    ||  CASE WHEN NOT (MAXDEGREE = -1 AND PARENTSERVICECLASSNAME IS     NULL)
              AND NOT (MAXDEGREE = -2 AND PARENTSERVICECLASSNAME IS NOT NULL) THEN CHR(10) || '    MAXIMUM DEGREE '  || CASE MAXDEGREE WHEN -1 THEN 'NONE' WHEN -2 THEN 'DEFAULT' ELSE MAXDEGREE END ELSE '' END
    || CASE WHEN PREFETCHPRIORITY = ' ' THEN '' ELSE CHR(10) || 'PREFETCH PRIORITY'
        || CASE PREFETCHPRIORITY
            WHEN 'H' THEN ' HIGH'
            WHEN 'M' THEN ' MEDIUM'
            WHEN 'L' THEN ' LOW'
            ELSE '' END
        END
    || CASE WHEN OUTBOUNDCORRELATOR IS NULL THEN '' ELSE CHR(10) || 'OUTBOUND CORRELATOR ''' || OUTBOUNDCORRELATOR || '''' END
    || CASE WHEN BUFFERPOOLPRIORITY = ' ' THEN '' ELSE CHR(10) || 'BUFFERPOOL PRIORITY'
        || CASE BUFFERPOOLPRIORITY
            WHEN 'H' THEN ' HIGH'
            WHEN 'M' THEN ' MEDIUM'
            WHEN 'L' THEN ' LOW'
            ELSE '' END
        END
    || CASE WHEN COLLECTACTDATA = 'N' THEN '' ELSE CHR(10) || 'COLLECT ACTIVITY DATA ON '
        || CASE COLLECTACTPARTITION WHEN 'C' THEN 'COORDINATOR MEMBER' WHEN 'D' THEN 'ALL MEMBERS' END
        || CASE COLLECTACTDATA 
                WHEN 'D' THEN ' WITH DETAILS'
                WHEN 'S' THEN ' WITH DETAILS SECTION'
                WHEN 'V' THEN ' WITH DETAILS SECTION INCLUDE ACTUALS BASE'
                WHEN 'X' THEN ' WITH DETAILS SECTION INCLUDE ACTUALS BASE AND VALUES'
                WHEN 'W' THEN ' WITHOUT DETAILS'
                WHEN 'N' THEN ' NONE'
                ELSE ''  END
        END
    || CASE WHEN COLLECTAGGACTDATA = 'N' THEN '' ELSE CHR(10) || 'COLLECT AGGREGATE ACTIVITY DATA NONE'
         || CASE COLLECTAGGACTDATA 
            WHEN 'B' THEN ' BASE'
            WHEN 'E' THEN ' EXTENDED'
            WHEN 'N' THEN ' NONE' -- default
            ELSE '' END
        END
    || CASE WHEN COLLECTAGGREQDATA = 'N' THEN '' ELSE CHR(10) || 'COLLECT AGGREGATE REQUEST DATA'
         || CASE COLLECTAGGREQDATA 
            WHEN 'B' THEN ' BASE'
            WHEN 'N' THEN ' NONE' -- default
            ELSE '' END
        END
    || CASE WHEN COLLECTAGGUOWDATA = 'N'  THEN '' ELSE CHR(10) || 'COLLECT AGGREGATE UNIT OF WORK DATA'
         || CASE COLLECTAGGUOWDATA 
            WHEN 'B' THEN ' BASE'
            WHEN 'N' THEN ' NONE' -- default
            ELSE '' END
        END
    || CASE WHEN COLLECTREQMETRICS = 'N' THEN '' ELSE CHR(10) || 'COLLECT REQUEST METRICS'
         || CASE COLLECTREQMETRICS 
            WHEN 'B' THEN ' BASE' 
            WHEN 'E' THEN ' EXTENDED'
            WHEN 'N' THEN ' NONE'  -- default
            ELSE '' END
        -- to-add - Histogram clause
        END
    AS DDL
FROM
    SYSCAT.SERVICECLASSES S
--LEFT JOIN SYSCAT.HISTOGRAMTEMPLATEUSE  -- TO-DO
