--# Copyright IBM Corp. All Rights Reserved.
--# SPDX-License-Identifier: Apache-2.0

/*
 * Activation/quiesce status of database members. Shows if database is explicitly activated and last activation time
 */

CREATE OR REPLACE VIEW DB_STATUS AS
SELECT 
    DB_STATUS
,   DB_ACTIVATION_STATE
,   DB_CONN_TIME            AS DB_ACTIVATION_TIME
--,   LAST_BACKUP
,   LISTAGG(MEMBER,',') WITHIN GROUP (ORDER BY MEMBER) AS MEMBERS
,          DAYS_BETWEEN(CURRENT_TIMESTAMP, DB_CONN_TIME)       AS DAYS
,   MOD(  HOURS_BETWEEN(CURRENT_TIMESTAMP, DB_CONN_TIME),24)   AS HOURS
,   MOD(MINUTES_BETWEEN(CURRENT_TIMESTAMP, DB_CONN_TIME),60) AS MINUTES
,   MOD(SECONDS_BETWEEN(CURRENT_TIMESTAMP, DB_CONN_TIME),60) AS SECONDS
FROM
    TABLE(MON_GET_DATABASE(-2))
GROUP BY
    DB_STATUS
,   DB_ACTIVATION_STATE
,   DB_CONN_TIME
--,   LAST_BACKUP