--# Copyright IBM Corp. All Rights Reserved.
--# SPDX-License-Identifier: Apache-2.0

/*
 * Current SQL by sortheap usage
 */

CREATE OR REPLACE VIEW DB_SORTHEAP_USAGE AS
SELECT * FROM(
SELECT
     MAX(VARCHAR(STMT_TEXT,32000))      AS STMT_TEXT
,    APPLICATION_HANDLE
,    SUM(SORT_HEAP_TOP)             * 4 / 1024  AS SORTHEAP_MB            
,    SUM(SORT_SHRHEAP_TOP)          * 4 / 1024  AS SHR_HEAP_MB            -- Total SHEAPTHRES_SHR consumed by this SQL
,    SUM(SORT_CONSUMER_SHRHEAP_TOP) * 4 / 1024  AS SHR_HEAP_CONS_MB       -- Highest SHEAPTHRES_SHR consumed by any one opeartor
,    MAX(ACTIVITY_STATE)                AS ACTIVITY_STATE
,    MAX(QUERY_COST_ESTIMATE)           AS QUERY_COST_ESTIMATE
,    MAX(ACTIVITY_TYPE)                 AS ACTIVITY_TYPE
,    SUM(ACTIVE_SORTS_TOP)              AS ACTIVE_SORTS_TOP
,    SUM(ACTIVE_SORT_CONSUMERS_TOP)     AS ACTIVE_SORT_CONSUMERS_TOP
,    SUM(ESTIMATED_SORT_CONSUMERS_TOP)  AS ESTIMATED_SORT_CONSUMERS_TOP
,    SUM(ESTIMATED_SORT_SHRHEAP_TOP)    AS ESTIMATED_SORT_SHRHEAP_TOP
,    SUM(POST_SHRTHRESHOLD_SORTS)       AS POST_SHRTHRESHOLD_SORTS
,    SUM(POST_THRESHOLD_SORTS)          AS POST_THRESHOLD_SORTS
/*10.5*/,    SUM(SORT_CONSUMER_HEAP_TOP)    AS SORT_CONSUMER_HEAP_TOP
/*10.5*/,    SUM(SORT_CONSUMER_SHRHEAP_TOP) AS SORT_CONSUMER_SHRHEAP_TOP
,    SUM(SORT_OVERFLOWS)                AS SORT_OVERFLOWS
,    SUM(TOTAL_SECTION_SORTS)           AS TOTAL_SECTION_SORTS
,    SUM(TOTAL_SECTION_SORT_PROC_TIME)  AS TOTAL_SECTION_SORT_PROC_TIME
,    SUM(TOTAL_SECTION_SORT_TIME)       AS TOTAL_SECTION_SORT_TIME
,    SUM(TOTAL_SORTS)                   AS TOTAL_SORTS
--
,    UOW_ID
,    ACTIVITY_ID
,    MAX(COORD_MEMBER)                  AS COORD_MEMBER
FROM
/*DB=*/     TABLE(MON_GET_ACTIVITY(NULL, -2)) 
GROUP BY
     APPLICATION_HANDLE
,    UOW_ID
,    ACTIVITY_ID   
ORDER BY
    SUM(SORT_SHRHEAP_TOP) DESC)SS
    