--# Copyright IBM Corp. All Rights Reserved.
--# SPDX-License-Identifier: Apache-2.0

/*
 * Returns the size of each tablespaces that has been touched since the last Db2 restart
 */

CREATE OR REPLACE VIEW DB_TABLESPACE_QUICK_SIZE AS 
SELECT  
     TBSP_NAME
,    ROUND(100 * (DECFLOAT(S.TBSP_USED_PAGES) / S.TBSP_USABLE_PAGES),2)     AS PCT_USED
,    INTEGER(ROUND((S.TBSP_USED_PAGES   * TBSP_PAGE_SIZE) /1073741824.0,0)) AS USED_GB
,    INTEGER(ROUND((S.TBSP_USABLE_PAGES * TBSP_PAGE_SIZE) /1073741824.0,0)) AS USABLE_GB
,    INTEGER(ROUND((S.TBSP_PAGE_TOP     * TBSP_PAGE_SIZE) /1073741824.0,0)) AS HWM_GB
,    BIGINT(ROUND((S.TBSP_MAX_SIZE     * TBSP_PAGE_SIZE) /1073741824.0,0))  AS MAX_GB
,    DATASLICES
,    INTEGER(ROUND((S.TBSP_MAX_USED_PAGES * DATASLICES * TBSP_PAGE_SIZE) /BIGINT(1073741824),0))    AS SKEW_USED_GB
,    INTEGER(ROUND((S.TBSP_MAX_USABLE_PAGES * DATASLICES * TBSP_PAGE_SIZE) /BIGINT(1073741824),0))  AS SKEW_USABLE_GB
,    INTEGER(ROUND((S.TBSP_MAX_PAGE_TOP     * DATASLICES * TBSP_PAGE_SIZE) /BIGINT(1073741824),0))  AS SKEW_HWM_GB
FROM
(   SELECT
        TBSP_NAME
    ,   MAX(TBSP_PAGE_SIZE) AS TBSP_PAGE_SIZE
    ,   SUM(BIGINT(TBSP_USABLE_PAGES))  AS TBSP_USABLE_PAGES
    ,   MAX(BIGINT(TBSP_USABLE_PAGES))  AS TBSP_MAX_USABLE_PAGES
    ,   SUM(BIGINT(TBSP_USED_PAGES))    AS TBSP_USED_PAGES
    ,   MAX(BIGINT(TBSP_USED_PAGES))    AS TBSP_MAX_USED_PAGES
    ,   SUM(BIGINT(TBSP_PAGE_TOP))      AS TBSP_PAGE_TOP
    ,   MAX(BIGINT(TBSP_PAGE_TOP))      AS TBSP_MAX_PAGE_TOP
    ,   SUM(BIGINT(TBSP_FREE_PAGES))    AS TBSP_FREE_PAGES
    ,   NULLIF(MAX(SUM(BIGINT(TBSP_MAX_SIZE)),0),0)      AS TBSP_MAX_SIZE
    ,   COUNT(*)                        AS DATASLICES
    FROM   
        TABLE(MON_GET_TABLESPACE(NULL,-2)) S
    GROUP BY
        TBSP_NAME
) AS S
