--# Copyright IBM Corp. All Rights Reserved.
--# SPDX-License-Identifier: Apache-2.0

/*
 * Lists all table functions, and generates SQL to select from them
 */

CREATE OR REPLACE VIEW DB_TABLE_FUNCTIONS AS
SELECT
    ROUTINESCHEMA       AS TABSCHEMA
,   ROUTINEMODULENAME
,   ROUTINENAME         AS TABNAME
,   SPECIFICNAME
,   'SELECT *'||                                 ' FROM TABLE( ' ||  R.ROUTINENAME || ' (' || COALESCE(PARMS,'') || '))s' AS SELECT_STAR_STMT
,   'SELECT ' || COALESCE(COLS,'*') || CHR(10) || 'FROM TABLE( ' ||  R.ROUTINENAME || ' (' || COALESCE(PARMS,'') || '))s' AS SELECT_COLS_STMT
FROM
    SYSCAT.ROUTINES R
LEFT JOIN
(   SELECT
        ROUTINESCHEMA
    ,   ROUTINENAME
    ,   SPECIFICNAME
    ,   LISTAGG(CAST('' AS VARCHAR(32000 OCTETS)) 
              || COALESCE(
                LOWER(RTRIM(PARMNAME)) || ' =>' || CASE WHEN PARMNAME IN ('DBPARTITIONNUM') THEN ' -2' ELSE ' DEFAULT' END
            ,':'||TRIM(P.ORDINAL))
            ,', ') WITHIN GROUP ( ORDER BY P.ORDINAL)  AS PARMS
    FROM
        SYSCAT.ROUTINEPARMS P
    WHERE
        P.ROWTYPE IN ('B','O','P')
    GROUP BY
        ROUTINESCHEMA
    ,   ROUTINENAME
    ,   SPECIFICNAME
) P
    USING
    ( ROUTINESCHEMA, ROUTINENAME, SPECIFICNAME )
LEFT JOIN
(   SELECT
        ROUTINESCHEMA
    ,   ROUTINENAME
    ,   SPECIFICNAME
    ,   LISTAGG(CAST('' AS VARCHAR(32000 OCTETS)) || PARMNAME,' ,') WITHIN GROUP ( ORDER BY P.ORDINAL)  AS COLS
    FROM
        SYSCAT.ROUTINEPARMS P
    WHERE
        P.ROWTYPE IN ('R','C','S')
    AND P.PARMNAME IS NOT NULL
    GROUP BY
        ROUTINESCHEMA
    ,   ROUTINENAME
    ,   SPECIFICNAME
) P
    USING
    ( ROUTINESCHEMA, ROUTINENAME, SPECIFICNAME )
WHERE
    R.ROUTINETYPE = 'F'
AND R.ORIGIN IN ('Q','E')
--AND R.ROUTINESCHEMA = 'SYSPROC'
--AND R.ROUTINENAME NOT LIKE '%\_V97%' ESCAPE '\'
--AND R.ROUTINENAME NOT LIKE '%\_V91%' ESCAPE '\'
--AND R.ROUTINENAME NOT LIKE 'HEALTH_'
--AND SUBSTR(R.ROUTINENAME,1,5) <> 'SNAP_'
