--# Copyright IBM Corp. All Rights Reserved.
--# SPDX-License-Identifier: Apache-2.0

/*
 * Lists all temporal tables 
 * 
 * Note that the TEMPORALTYPE in SYSCAT.TABLES is not accurate when the table is MAINTAINED BY USER
 * 
 */

CREATE OR REPLACE VIEW DB_TEMPORAL_TABLES AS
SELECT
     T.TABSCHEMA
,    T.TABNAME
,    T.TEMPORALTYPE
,    CASE WHEN BT.BEGINCOLNAME IS NOT NULL AND ST.BEGINCOLNAME IS NOT NULL THEN 'Bitemporal table'
          WHEN BT.BEGINCOLNAME IS NOT NULL                                 THEN 'Application-period temporal table'
          WHEN                                 ST.BEGINCOLNAME IS NOT NULL THEN 'System-period temporal table'
     END AS TEMPORAL_TYPE
,    CASE WHEN SUBSTR(T.PROPERTY,29,1) = 'Y' THEN 'MAINTAINED BY USER' ELSE 'MAINTAINED BY SYSTEM' END    AS MAINTAINED_BY
,    BT.BEGINCOLNAME        BUSINESS_TIME_BEGIN_COLNAME
,    BT.ENDCOLNAME          BUSINESS_TIME_END_COLNAME
,    ST.BEGINCOLNAME        SYSTEM_TIME_BEGIN_COLNAME
,    ST.ENDCOLNAME          SYSTEM_TIME_END_COLNAME
FROM
    SYSCAT.TABLES    T
LEFT JOIN
    SYSCAT.PERIODS  BT 
ON
    T.TABSCHEMA = BT.TABSCHEMA AND T.TABNAME = BT.TABNAME AND BT.PERIODNAME = 'BUSINESS_TIME'
LEFT JOIN
    SYSCAT.PERIODS  ST 
ON
    T.TABSCHEMA = ST.TABSCHEMA AND T.TABNAME = ST.TABNAME AND ST.PERIODNAME = 'SYSTEM_TIME'
WHERE
    T.TEMPORALTYPE <> 'N' OR SUBSTR(PROPERTY,29,1) = 'Y'
    