--# Copyright IBM Corp. All Rights Reserved.
--# SPDX-License-Identifier: Apache-2.0

/*
 * Lists tablespaces showing page size, max size (if set) etc
 */

CREATE OR REPLACE VIEW DB_TABLESPACES AS 
SELECT
    T.TBSPACE
,   NULLIF(DECIMAL(M.TBSP_MAX_SIZE/(1024*1024*1024.0),9,1),0)   MAX_SIZE_PER_MEMBER_GB
,   M.SUM_MAX_SIZE/(1024*1024*1024) SUM_MAX_SIZE_GB
,   T.PAGESIZE/1024 || 'K'    AS PAGE_SIZE
,   T.EXTENTSIZE             AS EXTENT_SIZE
,   CASE WHEN T.DATATYPE = 'A' THEN 'REGULAR' 
         WHEN T.DATATYPE = 'L' THEN 'LARGE'
         WHEN T.DATATYPE = 'T' THEN 'SYSTEM TEMPORARY'
         WHEN T.DATATYPE = 'U' THEN 'USER TEMPORARY'
    END                                                    AS TBSPACE_TYPE
,   CASE WHEN TBSP_USING_AUTO_STORAGE =1 THEN 'AUTOMATIC STORAGE'
         WHEN T.TBSPACETYPE = 'D'  THEN 'DATABASE'
         WHEN T.TBSPACETYPE = 'S'  THEN 'SYSTEM'
         END                                                AS MANAGED_BY
,   T.SGNAME
,   T.DBPGNAME
,   B.BPNAME
,   D.DATASLICES
,   M.TBSP_STATE          
,   M.TBSP_TRACKMOD_STATE
,   COALESCE(t.REMARKS,'')      AS COMMENTS
FROM 
    SYSCAT.TABLESPACES T
INNER JOIN
    SYSCAT.BUFFERPOOLS B
ON
    T.BUFFERPOOLID = B.BUFFERPOOLID
LEFT OUTER JOIN
(	SELECT
	    TBSP_NAME
	,   MIN(TBSP_USING_AUTO_STORAGE)  AS TBSP_USING_AUTO_STORAGE
	,   MAX(TBSP_EXTENT_SIZE)         AS TBSP_EXTENT_SIZE
	,   MAX(TBSP_STATE)               AS TBSP_STATE
	,   MAX(TBSP_TRACKMOD_STATE)      AS TBSP_TRACKMOD_STATE
	,   MAX(TBSP_PAGE_SIZE)           AS TBSP_PAGE_SIZE
	,   MAX(TBSP_MAX_SIZE)            AS TBSP_MAX_SIZE
	,   NULLIF(SUM(CASE WHEN TBSP_MAX_SIZE = -1 THEN 0 ELSE TBSP_MAX_SIZE END),0) AS SUM_MAX_SIZE
	FROM
	       TABLE (MON_GET_TABLESPACE(NULL,-2)) T
    GROUP BY
       TBSP_NAME
) M
ON
    T.TBSPACE = M.TBSP_NAME
LEFT OUTER JOIN
(   SELECT
        DBPGNAME
    ,   LISTAGG(DBPARTITIONNUM, ',') WITHIN GROUP (ORDER BY DBPARTITIONNUM ASC) AS DATASLICES
    FROM 
        SYSCAT.DBPARTITIONGROUPDEF
    GROUP BY 
        DBPGNAME
) D
ON
    T.DBPGNAME = D.DBPGNAME
    