--# Copyright IBM Corp. All Rights Reserved.
--# SPDX-License-Identifier: Apache-2.0

/*
 * Shows currently queued queries and estimated sortheap requirements 
 * 
*/

CREATE OR REPLACE VIEW DB_WLM_QUEUED_ACTIVITY AS
WITH TOTAL_MEM(CFG_MEM) AS (SELECT BIGINT(MAX(VALUE)) FROM SYSIBMADM.DBCFG WHERE NAME = 'sheapthres_shr' ) 
SELECT A.APPLICATION_HANDLE
,    A.UOW_ID
,    A.ACTIVITY_ID
,    A.ENTRY_TIME
,    TIMESTAMPDIFF(2
,    (CURRENT_TIMESTAMP - A.ENTRY_TIME)) AS TIME_QUEUED_SECONDS
,    B.APPLICATION_NAME
,    B.SESSION_AUTH_ID
,    B.CLIENT_IPADDR
,    A.ACTIVITY_STATE
,    A.ESTIMATED_SORT_SHRHEAP_TOP                                      AS EST_MEM_USAGE
,    A.MEMBER
,    DEC((FLOAT(A.ESTIMATED_SORT_SHRHEAP_TOP)/FLOAT(CFG_MEM))*100,5,2) AS EST_QUERY_PCT_MEM_USAGE
,    STMT_TEXT
FROM TABLE(MON_GET_ACTIVITY  (NULL,-2)) AS A
,    TABLE(MON_GET_CONNECTION(NULL,-2)) AS B
,    TOTAL_MEM C
WHERE (A.APPLICATION_HANDLE = B.APPLICATION_HANDLE)
AND (A.MEMBER = B.MEMBER)
AND (A.ACTIVITY_STATE = 'QUEUED')
AND (A.MEMBER=A.COORD_PARTITION_NUM)
--AND (DEC((FLOAT(A.ESTIMATED_SORT_SHRHEAP_TOP)/FLOAT(CFG_MEM))*100,5,2)) > 25
-- ORDER BY EST_MEM_USAGE DESC