--# Copyright IBM Corp. All Rights Reserved.
--# SPDX-License-Identifier: Apache-2.0

/*
 * Shows the most constrained WLM resource (threads vs sort)
 * 
 */

CREATE OR REPLACE VIEW DB_WLM_CONSTRAINED_RESOURCE AS
SELECT
    MAX(DEC((FLOAT(SORT_SHRHEAP_ALLOCATED)/FLOAT(SHEAPTHRES_SHR))*100, 5,2)) AS SORTMEM_USED_PCT
,   MAX(DEC((FLOAT(STMTS)/FLOAT(LOAD_TRGT))*100,5,2))                        AS THREADS_USED_PCT
FROM
    (SELECT MAX(VALUE) AS LOAD_TRGT                          FROM SYSIBMADM.DBCFG WHERE NAME = 'wlm_agent_load_trgt')
,   (SELECT VALUE AS SHEAPTHRES_SHR , MEMBER AS SHEAP_MEMBER FROM SYSIBMADM.DBCFG WHERE NAME = 'sheapthres_shr'     )
,   (SELECT SORT_SHRHEAP_ALLOCATED  , MEMBER AS ALLOC_MEMBER FROM TABLE(MON_GET_DATABASE(-2)))
,   (
        SELECT COUNT(*) AS STMTS
        FROM TABLE(MON_GET_ACTIVITY(NULL,-2)) 
        WHERE 
            ADM_BYPASSED = 0
        AND ACTIVITY_STATE IN ('EXECUTING','IDLE')
        AND MEMBER = COORD_PARTITION_NUM
    )
WHERE
    SHEAP_MEMBER = ALLOC_MEMBER
