--# Copyright IBM Corp. All Rights Reserved.
--# SPDX-License-Identifier: Apache-2.0

/*
 * Shows percentage of statements queued and queue time at a database member level
 * 
 */

CREATE OR REPLACE VIEW DB_WLM_QUEUING_SUMMARY AS
SELECT
    MEMBER
,   ACT_COMPLETED_TOTAL         AS STMTS_COMPLETED
,   ACT_ABORTED_TOTAL           AS STMTS_FAILED
,   WLM_QUEUE_ASSIGNMENTS_TOTAL AS STMTS_QUEUED
,   DEC((FLOAT(WLM_QUEUE_ASSIGNMENTS_TOTAL)/FLOAT(ACT_COMPLETED_TOTAL + ACT_ABORTED_TOTAL)) * 100, 5, 2) AS PCT_STMTS_QUEUED
,   TOTAL_APP_RQST_TIME /1000                                                                            AS TOTAL_RQST_TIME_SEC
,   TOTAL_APP_RQST_TIME / NULLIF((ACT_COMPLETED_TOTAL + ACT_ABORTED_TOTAL),0)                            AS AVG_RQST_TIME_MS
,   WLM_QUEUE_TIME_TOTAL AS TOTAL_QUEUE_TIME_MS, WLM_QUEUE_TIME_TOTAL / NULLIF(WLM_QUEUE_ASSIGNMENTS_TOTAL,0)      AS AVG_QUEUE_TIME_MS
FROM
    TABLE(MON_GET_DATABASE(-2)) AS T
