--# Copyright IBM Corp. All Rights Reserved.
--# SPDX-License-Identifier: Apache-2.0

/*
 * WLM Workload DDL 
 */

CREATE OR REPLACE VIEW DB_WORKLOAD_DDL AS
SELECT
    WORKLOADNAME
,   'CREATE WORKLOAD "' || WORKLOADNAME || '" ' || COALESCE(ATTRIBUTES,'')
    || CHR(10) || 'POSITION AT ' || EVALUATIONORDER
    || CASE WHEN ENABLED = 'N'        THEN '' ELSE CHR(10) ||'DISABLE' END
    || CASE WHEN ALLOWACCESS = 'N'    THEN '' ELSE CHR(10) ||'DISALLOW DB ACCESS' END
    || CASE WHEN MAXDEGREE = -1       THEN '' ELSE CHR(10) ||'MAXIMUM DEGREE ' || MAXDEGREE  END
    || CASE WHEN PARENTSERVICECLASSNAME = 'SYSDEFAULTUSERCLASS'
             AND SERVICECLASSNAME       = 'SYSDEFAULTSUBCLASS'
                                      THEN '' ELSE CHR(10) || 'SERVICE CLASS "' || SERVICECLASSNAME || '"' || COALESCE('UNDER "' || PARENTSERVICECLASSNAME || '"','') END 
    || CASE WHEN COLLECTACTDATA = 'N' THEN '' ELSE CHR(10) || 'COLLECT ACTIVITY DATA ON '
        || CASE COLLECTACTPARTITION WHEN 'C' THEN 'COORDINATOR MEMBER' WHEN 'D' THEN 'ALL MEMBERS' END
        || CASE COLLECTACTDATA 
                WHEN 'D' THEN ' WITH DETAILS'
                WHEN 'S' THEN ' WITH DETAILS SECTION'
                WHEN 'V' THEN ' WITH DETAILS SECTION INCLUDE ACTUALS BASE'
                WHEN 'X' THEN ' WITH DETAILS SECTION INCLUDE ACTUALS BASE AND VALUES'
                WHEN 'W' THEN ' WITHOUT DETAILS'
                WHEN 'N' THEN ' NONE'
                ELSE ''  END
        END
    || CASE WHEN COLLECTACTMETRICS = 'N'  THEN '' ELSE CHR(10) || 'COLLECT ACTIVITY METRICS '
         || CASE COLLECTACTMETRICS 
            WHEN 'B' THEN ' BASE'
            WHEN 'E' THEN ' EXTENDED'
            WHEN 'N' THEN ' NONE' -- default
            ELSE '' END
        END
    || CASE WHEN COLLECTUOWDATA <> 'N'    THEN '' ELSE CHR(10) || 'COLLECT UNIT OF WORK DATA '
         || CASE COLLECTUOWDATA 
            WHEN 'B' THEN ' BASE'
            WHEN 'P' THEN ' BASE INCLUDE '  || SUBSTR(COLLECTUOWDATAOPTIONS,2) -- not tested
            WHEN 'N' THEN ' NONE' -- default
            ELSE '' END
        END
    || CASE WHEN COLLECTAGGACTDATA = 'N'  THEN '' ELSE CHR(10) || 'COLLECT AGGREGATE ACTIVITY'
         || CASE COLLECTAGGACTDATA 
            WHEN 'B' THEN ' BASE' 
            WHEN 'E' THEN ' EXTENDED'
            WHEN 'N' THEN ' NONE'  -- default
            ELSE '' END
        END
    || CASE WHEN COLLECTAGGUOWDATA = 'N'  THEN '' ELSE CHR(10) || 'COLLECT AGGREGATE UNIT OF WORK DATA '
         || CASE COLLECTAGGUOWDATA 
            WHEN 'B' THEN ' BASE'
            WHEN 'N' THEN ' NONE' -- default
            ELSE '' END
        END
    || CASE WHEN COLLECTLOCKWAIT = 'N'    THEN '' ELSE CHR(10) || 'COLLECT LOCK WAIT DATA'
         || ' FOR LOCKS WAITING MORE THAN ' || CASE WHEN MOD(LOCKWAITVALUE,1000) = 0 THEN LOCKWAITVALUE / 1000 || ' SECONDS'  ELSE LOCKWAITVALUE * 1000 || ' MICROSECONDS' END
         || CASE COLLECTLOCKWAIT 
            WHEN 'H' THEN ' WITH HISTORY'
            WHEN 'V' THEN ' WITH HISTORY AND VALUES'
            WHEN 'W' THEN ' WITHOUT HISTORY'
            WHEN 'N' THEN ' NONE'-- default
            ELSE '' END
        END    
    || CASE WHEN COLLECTLOCKTIMEOUT = 'W' THEN '' ELSE CHR(10) || 'COLLECT LOCK TIMEOUT DATA' 
         || CASE COLLECTLOCKTIMEOUT 
            WHEN 'H' THEN ' WITH HISTORY'
            WHEN 'V' THEN ' WITH HISTORY AND VALUES'
            WHEN 'W' THEN ' WITHOUT HISTORY' -- default
            WHEN 'N' THEN ' NONE'
            ELSE '' END
        END
    || CASE WHEN COLLECTDEADLOCK = 'W'    THEN '' ELSE CHR(10) || 'COLLECT DEADLOCK DATA'
         || CASE COLLECTDEADLOCK 
            WHEN 'H' THEN ' WITH HISTORY'
            WHEN 'V' THEN ' WITH HISTORY AND VALUES'
            WHEN 'W' THEN ' WITHOUT HISTORY' -- default
            ELSE '' END
        END
--    || CASE WHEN THEN '' ELSE CHR(10) || 'ACTIVITY ESTIMATEDCOST HISTOGRAM TEMPLATE "' --SYSDEFAULTHISTOGRAM"
--    || CASE WHEN THEN '' ELSE CHR(10) || 'ACTIVITY EXECUTETIME HISTOGRAM TEMPLATE "' --SYSDEFAULTHISTOGRAM"
--    || CASE WHEN THEN '' ELSE CHR(10) || 'ACTIVITY INTERARRIVALTIME HISTOGRAM TEMPLATE ' --"SYSDEFAULTHISTOGRAM"
--    || CASE WHEN THEN '' ELSE CHR(10) || 'ACTIVITY LIFETIME HISTOGRAM TEMPLATE ' --"SYSDEFAULTHISTOGRAM"
--    || CASE WHEN THEN '' ELSE CHR(10) || 'ACTIVITY QUEUETIME HISTOGRAM TEMPLATE ' --"SYSDEFAULTHISTOGRAM"
--    || CASE WHEN THEN '' ELSE CHR(10) || 'UOW LIFETIME HISTOGRAM TEMPLATE ' --"SYSDEFAULTHISTOGRAM"@
        AS DDL
FROM
    SYSCAT.WORKLOADS W
LEFT JOIN
(
    SELECT
        WORKLOADID
    ,   LISTAGG(CHR(10) || '    ' || CONNATTRTYPE || '(''' || RTRIM(CONNATTRVALUE) || ''')')
            WITHIN GROUP( ORDER BY CONNATTRTYPE, CONNATTRVALUE)  AS ATTRIBUTES
    FROM
        SYSCAT.WORKLOADCONNATTR
    GROUP BY
        WORKLOADID
)
    AS A
USING ( WORKLOADID )
--LEFT JOIN SYSCAT.HISTOGRAMTEMPLATEUSE  -- TO-DO
