-- Script to migrate Q Apply control tables from V8.2 to V9.1.
--
-- Prior to running this script, customize it to your existing 
-- Q Apply server environment:
-- (1) Locate and change all occurrences of the string !appschema! 
--     to the name of the Q Apply schema applicable to your
--     environment
--

ALTER TABLE !appschema!.IBMQREP_APPLYPARMS VOLATILE CARDINALITY;
ALTER TABLE !appschema!.IBMQREP_RECVQUEUES VOLATILE CARDINALITY;
ALTER TABLE !appschema!.IBMQREP_TARGETS VOLATILE CARDINALITY;
ALTER TABLE !appschema!.IBMQREP_TRG_COLS VOLATILE CARDINALITY;
ALTER TABLE !appschema!.IBMQREP_SPILLQS VOLATILE CARDINALITY;
ALTER TABLE !appschema!.IBMQREP_APPLYTRACE VOLATILE CARDINALITY;
ALTER TABLE !appschema!.IBMQREP_APPLYMON VOLATILE CARDINALITY;
ALTER TABLE !appschema!.IBMQREP_SPILLEDROW VOLATILE CARDINALITY;
ALTER TABLE !appschema!.IBMQREP_SAVERI VOLATILE CARDINALITY;

--
-- Changes to control tables for Version 9
--
ALTER TABLE !appschema!.IBMQREP_APPLYPARMS DROP CHECK CA_MON_LIMIT;
ALTER TABLE !appschema!.IBMQREP_APPLYPARMS DROP CHECK CA_TRACE_LIMT;
ALTER TABLE !appschema!.IBMQREP_APPLYPARMS DROP CHECK CA_MON_INTERVAL;
ALTER TABLE !appschema!.IBMQREP_APPLYPARMS DROP CHECK CA_PRUNE_INTERVAL;
ALTER TABLE !appschema!.IBMQREP_APPLYPARMS DROP CHECK CA_AUTOSTOP;
ALTER TABLE !appschema!.IBMQREP_APPLYPARMS DROP CHECK CA_LOGREUSE;
ALTER TABLE !appschema!.IBMQREP_APPLYPARMS DROP CHECK CA_LOGSTDOUT;
ALTER TABLE !appschema!.IBMQREP_APPLYPARMS DROP CHECK CA_TERM;
ALTER TABLE !appschema!.IBMQREP_APPLYPARMS DROP CHECK CA_RETRIES;

ALTER TABLE !appschema!.IBMQREP_APPLYPARMS
  ADD COLUMN SQL_CAP_SCHEMA VARCHAR(128) WITH DEFAULT NULL;
ALTER TABLE !appschema!.IBMQREP_APPLYPARMS
  ALTER COLUMN ARCH_LEVEL SET DEFAULT '0901'
  ALTER COLUMN MONITOR_INTERVAL SET DEFAULT 300000;


ALTER TABLE !appschema!.IBMQREP_RECVQUEUES 
  DROP CHECK CC_SENDQ_STATE;
ALTER TABLE !appschema!.IBMQREP_RECVQUEUES
  ALTER COLUMN CAPTURE_SCHEMA SET DATA TYPE VARCHAR(128);
ALTER TABLE !appschema!.IBMQREP_RECVQUEUES
  ADD COLUMN SOURCE_TYPE CHAR(1) WITH DEFAULT ' ';

ALTER TABLE !appschema!.IBMQREP_TARGETS
  DROP CHECK CA_TARGTBL_STATE
  DROP CHECK CA_UPDATEANY
  DROP CHECK CA_CONFLICTACTION
  DROP CHECK CA_ERRORACTION
  DROP CHECK CA_UPANY_SOURCE
  DROP CHECK CA_UPANY_TARGET
  DROP CHECK CA_TARGET_TYPE
  DROP CHECK CA_GROUP_INIT_ROLE
  DROP CHECK CA_LOAD_TYPE;
ALTER TABLE !appschema!.IBMQREP_TARGETS
  ADD COLUMN MODELQ VARCHAR(36) WITH DEFAULT 'IBMQREP.SPILL.MODELQ'
  ADD COLUMN CCD_CONDENSED CHARACTER(1) WITH DEFAULT 'N'
  ADD COLUMN CCD_COMPLETE CHARACTER(1) WITH DEFAULT 'N';
ALTER TABLE !appschema!.IBMQREP_TARGETS
  ADD COLUMN SOURCE_TYPE CHAR(1) WITH DEFAULT ' ';

ALTER TABLE !appschema!.IBMQREP_TRG_COLS
  DROP CHECK CA_IS_KEY;
ALTER TABLE !appschema!.IBMQREP_TRG_COLS
  ALTER COLUMN SOURCE_COLNAME SET DATA TYPE VARCHAR(254);
ALTER TABLE !appschema!.IBMQREP_TRG_COLS
  ADD COLUMN MAPPING_TYPE CHAR(1) WITH DEFAULT NULL
  ADD COLUMN SRC_COL_MAP VARCHAR(2000) WITH DEFAULT NULL
  ADD COLUMN BEF_TARG_COLNAME VARCHAR(128) WITH DEFAULT NULL;


ALTER TABLE !appschema!.IBMQREP_EXCEPTIONS
  DROP CHECK CA_IS_APPLIED;

-- after executing the below mentioned alter sql, a reorg of the 
-- !appschema!.IBMQREP_EXCEPTIONS table is required be for starting QApply.
-- Otherwise QApply will fail with sqlcode -668 when a subscription 
-- exception is encountered.

ALTER TABLE !appschema!.IBMQREP_EXCEPTIONS
  ALTER COLUMN SRC_COMMIT_LSN SET DATA TYPE VARCHAR(48);

ALTER TABLE !appschema!.IBMQREP_APPLYMON
  ADD COLUMN OLDEST_INFLT_TRANS TIMESTAMP;

ALTER TABLE !appschema!.IBMQREP_SAVERI
  DROP CHECK CA_TYPE_OF_LOAD;
ALTER TABLE !appschema!.IBMQREP_SAVERI
  ALTER COLUMN CONSTNAME SET DATA TYPE VARCHAR(128);
ALTER TABLE !appschema!.IBMQREP_SAVERI
  ADD COLUMN DELETERULE CHAR(1) WITH DEFAULT NULL
  ADD COLUMN UPDATERULE CHAR(1) WITH DEFAULT NULL; 

UPDATE !appschema!.IBMQREP_APPLYPARMS SET ARCH_LEVEL = '0901';

UPDATE !appschema!.IBMQREP_TARGETS SET TARGET_TYPE = 1 
      WHERE TARGET_TYPE=3;

UPDATE !appschema!.IBMQREP_TRG_COLS SET MAPPING_TYPE = 'R';

--
-- Starting V9.1, the values in the MONITOR_INTERVAL column
-- are interpreted as milliseconds. They were interpreted
-- as seconds in Version 8.
-- The following UPDATE statement is to change the unit
-- from second to millisecond by multiplying the current
-- values by 1000 during the migration of the control
-- tables from Version 8 to Version 9.1.

UPDATE !appschema!.IBMQREP_APPLYPARMS
  SET MONITOR_INTERVAL = MONITOR_INTERVAL * 1000;
